### ISSUE TITLE
NerdPress menu shows options to clear both caches

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#105]
![image](https://user-images.githubusercontent.com/24479276/84309927-af2f5880-ab15-11ea-81a8-c5d09040813e.png)

In the screenshot above, the plugin was configured to use Sucuri. It should only show `Clear Cloudflare Cache` when the radio button is set to Cloudflare, AND the API Token is defined.

**Comment by blogtutor** [comment]
`Clear Cloudflare Cache` is also displaying when "None/Other" is selected.

**Comment by ecotechie** [comment]
Done.
