### ISSUE TITLE
Need better error handling for invalid Cloudflare API responses

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#109]
**We need to find a way so that no matter what the API response is (or if there's no response), we won't have a fatal error.**

Cloudflare's API had [an outage a couple of weeks ago](https://www.cloudflarestatus.com/incidents/gystdkg4p0k3).

Some errors were correctly formed JSON error responses. Others were 5xx HTML error pages.

We also saw some **more 5xx HTML error pages** returned today through the Zapier webhook into Slack.

We're also sometimes seeing a **"no healthy upstream"** error in the Slack alert. Hannes at Cloudflare said that this is not a response from Cloudflare, so that may be something Zapier is adding/reporting?

![image](https://user-images.githubusercontent.com/24479276/84527760-584f8d80-ac93-11ea-8ef5-4540147be18d.png)

This is from muybuenocookbook.com (She got this via email May 26 @ 1:22pm Pacific):
```
Error Details
=============
An error of type E_ERROR was caused in line 390 of the file
/home/nginx/domains/muybuenocookbook.com/public/wp-content/plugins/cloudflare-enterprise-integration/nerdpress-cf.php.
Error message: Uncaught Error: Cannot use object of type WP_Error as
array in /home/nginx/domains/muybuenocookbook.com/public/wp-content/plugins/cloudflare-enterprise-integration/nerdpress-cf.php:390
Stack trace:
#0 /home/nginx/domains/muybuenocookbook.com/public/wp-content/plugins/cloudflare-enterprise-integration/nerdpress-cf.php(425):
CFClient::processResponse('CFClient::purge...', Object(WP_Error))
#1 /home/nginx/domains/muybuenocookbook.com/public/wp-content/plugins/cloudflare-enterprise-integration/nerdpress-cf.php(439):
CFClient::purgeCache()
#2 /home/nginx/domains/muybuenocookbook.com/public/wp-includes/class-wp-hook.php(287):
CFClient->handlePostCacheTransition('publish', 'publish',
Object(WP_Post))
#3 /home/nginx/domains/muybuenocookbook.com/public/wp-includes/class-wp-hook.php(311):
WP_Hook->apply_filters(NULL, Array)
#4 /home/nginx/domains/muybuenocookbook.com/public/wp-includes/plugin.php(478):
WP_Hook->do_action(Array)
#5 /home/nginx/domains/muybuenocookbook.com/public/wp-includes/post.php(4667):
do_action('tr
```

Sample Errors in Slack:
https://nerd-press.slack.com/archives/C010P9N9P28/p1590524220021100
https://nerd-press.slack.com/archives/C010P9N9P28/p1590524408021800
https://nerd-press.slack.com/archives/C010P9N9P28/p1591978225007700

**Comment by blogtutor** [comment]
The PHP Error should have been fixed with the old plugin, here:
https://github.com/blogtutor/cloudflare-enterprise-integration/issues/26
https://github.com/blogtutor/cloudflare-enterprise-integration/commit/92f985d0a0ff58caab345290f690d7600459bf74

BUT we still need to handle other errors (5xx HTML responses and "no healthy upstream") better.

Also, not even sure where "no healthy upstream" is coming from...

**Comment by ecotechie** [comment]
I'm thinking we check if an error is not in array form and then just call it an error. So it doesn't break the reporting or site.

**Comment by blogtutor** [comment]
As long as we still send a useful error message to the Zapier webhook... not sure if it really does any harm to send the full HTML to Zapier (since that really just goes to us).  My bigger concern is making sure any errors don't cause actual issues on the client site.

**Comment by ecotechie** [comment]
I'm thinking changing this:
https://github.com/blogtutor/blog-tutor-support/blob/master/includes/class-support-cloudflare.php#L295

```
if ( ! defined( 'NP_SUPPRESS_NOTIFICATION' ) )
	self::storeResult( $result['body'] );
return 'success';
}
```

to

```
if ( ! defined( 'NP_SUPPRESS_NOTIFICATION' ) ) {
        if ( is_array( $result ) && isset( $result['body']  ) ) {
        	self::storeResult( $result['body'] );
        } else {
                self::storeResult( 'There was a problem clearing the Cloudflare cache, please contact support' );
        }
        return 'success';
}
```

**Comment by blogtutor** [comment]
Hmm. That `return 'success'` is I think what the javascript looks for to show the success message, right?  So I'm not sure if that's what we should be returning in both cases?  Maybe we should go through this on zoom...

**Comment by blogtutor** [comment]
This isn't a common enough problem to worry about, closing.
