### ISSUE TITLE
PHP Warnings on Microsoft Server

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#111]
On plowingthrouhglife.com, which is running a Windows server - When `WP_DEBUG` is enabled, we're getting these warnings. Perhaps best if we just disable all the disk space stuff if the `sys_getloadavg` doesn't exist?

I think we need to do that check on Settings > System Info, and also for the admin toolbar display.

`[14-Jun-2020 14:54:12 UTC] PHP Warning:  Division by zero in D:\inetpub\plowingthroughlife\wp-content\plugins\blog-tutor-support\includes\class-support-helpers.php on line 73`

`[14-Jun-2020 14:54:16 UTC] PHP Warning:  disk_free_space(): The directory name is invalid.
 in D:\inetpub\plowingthroughlife\wp-content\plugins\blog-tutor-support\includes\class-support-helpers.php on line 67`

`[14-Jun-2020 14:54:16 UTC] PHP Warning:  disk_total_space(): The directory name is invalid.
 in D:\inetpub\plowingthroughlife\wp-content\plugins\blog-tutor-support\includes\class-support-helpers.php on line 69`

`[14-Jun-2020 14:54:16 UTC] PHP Notice:  Undefined index: HTTP_X_REAL_IP in D:\inetpub\plowingthroughlife\wp-content\plugins\blog-tutor-support\includes\admin\views\html-serverinfo-field.php on line 104`

**Comment by ecotechie** [comment]
I was using disk_free_space( __FILE__ );  Trying disk_free_space( __DIR__ ); instead. The last error is from something else. I'll fix that now too.
