### ISSUE TITLE
Visual improvements to Cloudflare Cache Clear dashboard notice

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#112]
![image](https://user-images.githubusercontent.com/24479276/84597120-7396d600-ae16-11ea-9966-d589ca531788.png)

1. Let's change "NerdPress Cloudflare Enterprise Integration" to something a little less clunky?

2. Can we add the NerdPress icon?  (I'd still keep the side color of red/green the same, based on success/errors, though).

**Comment by ecotechie** [comment]
How does NerdPress Cloudflare sound instead? Or keep the Enterprise part too...

**Comment by blogtutor** [comment]
I suppose it's really just a "NerdPress Notification," right?  How about we change the heading to that, and then change the "Successfully cleared to include the word Enterprise?

Headline: NerdPress Notification
Text: Cloudflare Enterprise cache has been successfully cleared!

Open to other ideas if you don't love this...

**Comment by ecotechie** [comment]
Done

**Comment by blogtutor** [comment]
![image](https://user-images.githubusercontent.com/24479276/85343575-0df3bb00-b4a2-11ea-8725-45895ecd668d.png)

I think we should say "NerdPress Notification" (not "Notice") and also should not have a colon on it.
