### ISSUE TITLE
Add name of user that triggered a Cloudflare cache clear

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#117]
How about we include in the webhook data the name of the user that triggered a manual cache clear?

And for auto cache clears that are triggered by new comments, it might be helpful to have the ID of the actual comment? Not sure if that's necessary, though.

**Comment by blogtutor** [comment]
And, if a user updated a post (post transition publish -> publish), we could include the username as well for that.

**Comment by ecotechie** [comment]
Completed.
