### ISSUE TITLE
Replace terms "blacklist" and "whitelist"

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#118]
It's time for us to do a push to get rid of these terms... 

Suggested replacements - though I'm happy to brainstorm better ideas/options:

When used as verbs:
"block" instead of "blacklist"
"allow" instead of "whitelist"

When used as nouns:
"blocklist" instead of "blacklist"
"allowlist" instead of "whitelist"

**Comment by ecotechie** [comment]
Cleaned up code.
