### ISSUE TITLE
Hide auto-update interface in WP 5.5

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#125]
WordPress 5.5 will include an auto-update feature for core, plugins, and themes.  Because unattended updates are likely to be problematic if any new bugs are introduced, we do not want to enable this for sites we manage.

So we need to:

- by default, hide the auto-update interface for plugins & themes.  
- but, continue to show the interface for NerdPress users.
- and, allow us to re-enable the interface for clients who request it.

Further reading:
https://make.wordpress.org/core/2020/07/15/controlling-plugin-and-theme-auto-updates-ui-in-wordpress-5-5/
https://make.wordpress.org/core/2020/07/30/recommended-usage-of-the-updates-api-to-support-the-auto-updates-ui-for-plugins-and-themes-in-wordpress-5-5/
https://www.wordfence.com/blog/2020/08/wordpress-auto-updates-what-do-you-have-to-lose/

**Comment by blogtutor** [comment]
Tweak language per our zoom:

Title --> Description

Show Auto-Updates for Plugins --> Restores the auto-update user interface for plugins.

Show Auto-Updates for Themes --> Restores the auto-update user interface for themes.

**Comment by ecotechie** [comment]
Donezo!
