### ISSUE TITLE
Set debugging on through our interface.

### ISSUE THREAD

**Issue by ecotechie** [blogtutor/blog-tutor-support#128]
Add a checkbox to temporarily enable debugging to a file:

# Enable Debug logging

if ( ! WP_DEBUG && NerdPress_Helpers::is_nerdpress && NerdPress_Helpers::debug_on ) {
  define( 'WP_DEBUG', true );
  define( 'WP_DEBUG_LOG', false );
  define( 'WP_DEBUG_DISPLAY', true );
}

**Comment by blogtutor** [comment]
Also love the idea of automatically turning it off after a set amount of time, so we can't accidentally leave it on.

**Comment by ecotechie** [comment]
Why not have this only display logs on the dashboard for our user and not save them? Then we can leave this on all the time...

**Comment by blogtutor** [comment]
I'm not sure we'd really want to see all errors every time we're logged into a site - that can really muck things up, especially if the site happens to show a lot of warnings or deprecation notices.

But maybe a checkbox to enable debug display only (not logging)?

**Comment by ecotechie** [comment]
Not sure about this, since if the WP_DEBUG constant is already set in the config file you can't change it. Maybe if we add the check first. But this is outside of plugin territory... I think we should close this issue.
