### ISSUE TITLE
Create a tool/form field on settings page to clear Cloudproxy cache for individual files

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#13]
Would be nice for us to be able to purge an individual file quickly via the settings page.

It's possible to do this with the API, or from the Sucuri website. This way if we're tweaking a specific file, we don't have to purge the whole Cloudproxy cache to get changes to show up.

**Comment by ecotechie** [comment]
This is the API call to use:
https://waf.sucuri.net/api?&k=API_KEY&s=API_SECRET&a=clearcache&file=FILE_PATH

**Comment by blogtutor** [comment]
@ecotechie I think I saw you tinkering with this... Is it done?

**Comment by blogtutor** [comment]
@ecotechie Well, if we have it available for other admins, that means we'll need a settings page available ... how about for now we just put it on our settings page so it's accessible for us. we can always move it to a user-facing settings page later.

**Comment by ecotechie** [comment]
Some guidance for how to do this:
https://stackoverflow.com/questions/4446727/using-a-php-variable-in-a-text-input-value-statement

**Comment by blogtutor** [comment]
Probably just needs to be a regular HTML form with a GET or POST request to the correct API URL.

Also, add this to a new "Cloudproxy" tab on our settings page.

**Comment by ecotechie** [comment]
All set for testing:
https://github.com/blogtutor/blog-tutor-support/compare/98e0734af2db...1c28e3975caf

**Comment by blogtutor** [comment]
Works great! Releasing in 0.5.2.
