### ISSUE TITLE
Hide Shortpixel "Bulk Optimization" Tool

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#130]
I'd like to hide Shortpixel's "Bulk Optimization" tool for clients who are using our API keys.  

I sometimes will optimize the library in "Glossy" mode (especially if images have been optimized in the past by other, less effective techniques) -- and then will change to "Lossy" mode for new images going forward.  If the client then runs the bulk optimization again, it will reprocess the entire library in Lossy mode, which we want to avoid.  

I asked Shortpixel if there's a built-in way to hide the menu (such as setting a constant in wp-config.php), but apparently they don't provide that. So we'll need to track it down and hide the menu item ourselves.

We also need to be sure to allow it for Sleep Soundly clients who are using their own Shortpixel accounts.

**Comment by blogtutor** [comment]
Shortpixel support says this should do the trick:

```
add_action('admin_menu', function () {
remove_submenu_page('upload.php', 'wp-short-pixel-bulk');
}, 20);
```

Of course we'll still need to add a way to enable/disable that in our plugin (probably best to leave it disabled by default, and then for Inner Peace clients I can enable it during setup.)

**Comment by blogtutor** [comment]
@ecotechie  Small language tweaks on the settings page, please:

Instead of "ShortPixel Bulk Regenerate" please call the option "ShortPixel Bulk Optimization".

In the description, change it to "Hide Shortpixel Bulk Optimization from non-NerdPress users."

(it's bulk optimization, not bulk thumbnail regeneration)

**Comment by blogtutor** [comment]
I just had an idea on this, which I think will make things a lot easier on us, in terms of enabling/configuring this option.

For Inner Peace clients, we always hide the API key using a constant in wp-config.php.  How about we automatically hide the Shortpixel Bulk Menu if that constant is set?  This way as soon as the plugin is updated, the bulk menu will be hidden for all these clients.

And, for Sleep Soundly clients, we don't hide the API key - so they won't lose the bulk menu (and they shouldn't).

This is the constant... so if it's true (and it's not a NerdPress user), then we should hide the menu:

`define('SHORTPIXEL_HIDE_API_KEY', true);`

And then maybe we should have an option to override that in our settings?  So, that would basically flip the logic around of the current setting.

**Comment by ecotechie** [comment]
donezo
