### ISSUE TITLE
PHP Notice on Comment "Approve and Reply"

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#144]
This is reported on sweetestmenu.com.  When she does a comment "Approve and Reply" it triggers a notice that two Constants are already set.

I think it's because the "Approve" triggers a cache clear and the "Reply" triggers a separate cache clear -- and they're happening simultaneously in this case, causing a conflict.

Comments are still being approved/published, so it's not interfering with the work -- but I'm not sure if the cache is actually getting cleared.

![image](https://user-images.githubusercontent.com/24479276/106678948-924a0880-6570-11eb-9d0e-f052b5f3388c.png)

**Comment by blogtutor** [comment]
Jess just reported more issues on her site. 

Apparently this showed up when she bulk-deleted posts and then emptied the trash. (I'm trying to get more details of exactly when it happened, and if it actually broke the functionality or if it just displayed the notice and still deleted/trash things successfully).

![image](https://user-images.githubusercontent.com/24479276/106916486-152baa00-66bc-11eb-9d72-aa00e6918ffc.png)

**Comment by ecotechie** [comment]
Fixed here:
https://github.com/blogtutor/blog-tutor-support/commit/e63b918698cfa52ac0eacfa70cb6cfd037895685
