### ISSUE TITLE
Remove Sucuri Allowlist and Clear Cache form fields

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#145]
The Sucuri manual allowlisting and individual cache file clearing (inside the plugin Settings > Sucuri tab) is no longer working. 

Let's just remove them completely, since we can access these two features easily on waf.sucuri.net instead.

**Comment by blogtutor** [comment]
However, do NOT remove the tab entirely!  We still use this for the automatic allowlist feature.  We can just remove the two form fields inside the tab... these:

![image](https://user-images.githubusercontent.com/24479276/106813570-04305980-6626-11eb-80b0-74b4d5c219f6.png)

**Comment by ecotechie** [comment]
Why not remove this tab and add the auto allowlist feature to the server info tab?

**Comment by blogtutor** [comment]
I'd be inclined to just remove these two form fields that don't work anymore. Removing those would be very fast and easy, and less likely to break anything else by accident. I think there's potentially some benefit also of keeping the Sucuri tab -- since it's more obvious at a glance that the site is using Sucuri.

Considering that we're slowly phasing out Sucuri I'm thinking let's just remove these form fields and not spend any extra time on it.
