### ISSUE TITLE
Rate Limit Full Cloudflare Cache Clear Requests

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#149]
Sometimes when updating a published post, the Cloudflare Cache API call is triggered multiple times simultaneously.

Could not reproduce on our dev site, but we could on Southern Bytes.

**Comment by ecotechie** [comment]
This is from the block editor?

**Comment by blogtutor** [comment]
Yes, it doesn't seem to do it with the classic editor.  We looked into this a while back and couldn't track down what was triggering it multiple times.

I think a robust solution might be to save a timestamp in the database of the most recent full cache clear, and then just not clear the cache if the clear request is within ~10 seconds of the timestamp.  ?

**Comment by blogtutor** [comment]
Maybe helpful:
https://wordpress.org/support/topic/publish_post-hook-trigger-twice-when-i-publish-post/

**Comment by ecotechie** [comment]
@blogtutor so you want to make it so the timestamp is saved in a separate table?

**Comment by blogtutor** [comment]
no, just a separate option in the options table

**Comment by blogtutor** [comment]
`add_option( 'nerdpress_last_cache_clear', $date, '', $autoload = 'no' );`

(not sure if it should be autoloaded or not, but I'm guessing not.)

**Comment by blogtutor** [comment]
Done in 1.4.
