### ISSUE TITLE
Handle Cloudflare Cache clearing better for multi-language sites

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#151]
Sites using the WPML plugin for multi-language can create the alternate languages in subfolders.  When that content is updated, we need to remove that subfolder from the Custom Hostname that we send back to Cloudflare in the API request.

For example, `smartlittlecookiet.net/es/`

Her WPMU Settings:
![image](https://user-images.githubusercontent.com/24479276/115891069-843ab400-a40a-11eb-9010-0abf2a92fc92.png)

And this is the CF failure response:
![image](https://user-images.githubusercontent.com/24479276/115891029-784ef200-a40a-11eb-8209-797c0014be66.png)

So we need to strip out the `/es/` from the request... Let's discuss a strategy for doing this simply...

**Comment by ecotechie** [comment]
This really depends on how the multiple languages are being formatted.

**Comment by blogtutor** [comment]
This is only an issue for full cache clears -- and for that API request, it needs to be the Custom Hostname only in the API call.  So we can comfortably strip out _everything_ after the domain name on all requests for a full cache clear.

We just need to be careful not to change how single URL cache clears is done.
