### ISSUE TITLE
Exclude scripts from WP Rocket 3.9's "Delay JavaScript" feature

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#152]
WP Rocket support has confirmed we can use the `rocket_delay_js_exclusions` filter to exclude JavaScript from 3.9's "Delay JavaScript" feature.

At a minimum, let's exclude Google Analytics, AdThrive, and Mediavine...and probably any others that we've removed from the <3.9 default list.

**Comment by halounsbury** [comment]
Starting a list of the strings/scripts to exclude (may be more coming):

```
google-analytics.com/analytics.js
ga( '
ga('
/gtag/js
gtag(
/gtm.js
/gtm-
scripts.mediavine.com
ads.adthrive.com
nutrifox
flodesk
wp-recipe-maker
```

**Comment by blogtutor** [comment]
Also, Convert Pro's script should not be delayed by WP Rocket:

`cp-popup.js`

https://nerd-press.slack.com/archives/G81PJNZME/p1622579834024800

**Comment by blogtutor** [comment]
Add `slickstream` to the list.

https://www.slickstream.com/support/slickstream-and-wp-rocket

**Comment by blogtutor** [comment]
Add a setting in our settings page to be able to disable this function.

**Comment by blogtutor** [comment]
Here's the code we need to use...

```
// Exclude scripts from JS delay.
function np_wp_rocket__exclude_from_delay_js( $excluded_strings = array() ) {

        // MUST ESCAPE PERIODS AND PARENTHESES!
	$excluded_strings[] = 'google-analytics\.com/analytics\.js';
	$excluded_strings[] = "/gtag/";	
	$excluded_strings[] = "/gtm\.js";	
	$excluded_strings[] = "/gtm-";
	$excluded_strings[] = "ga\( '";
	$excluded_strings[] = "ga\('";
	$excluded_strings[] = "gtag\(";	
	$excluded_strings[] = "scripts\.mediavine\.com";
	$excluded_strings[] = "ads\.adthrive\.com";
	$excluded_strings[] = "nutrifox";
	$excluded_strings[] = "flodesk";
	$excluded_strings[] = "cp-popup\.js";
	$excluded_strings[] = "wp-recipe-maker";
	$excluded_strings[] = "slickstream";		
	return $excluded_strings;
}
add_filter( 'rocket_delay_js_exclusions', 'np_wp_rocket__exclude_from_delay_js' );```

**Comment by ecotechie** [comment]
Added to plugin's constructor

**Comment by blogtutor** [comment]
Reopening... need to add an option in our settings page to disable this exclusion.  Should be un-checked by default (so the strings are indeed excluded).

**Comment by blogtutor** [comment]
Added `social-pug` and released 1.0.2. 

https://nerd-press.slack.com/archives/C01DQ6EFQBW/p1625662256313600

**Comment by mikezielonka** [comment]
I started monitoring their official list: https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#exclusions

**Comment by mikezielonka** [comment]
WP Rocket changed what they recommend for GA

```
google-analytics.com/analytics.js
ga\( '
ga\('
```

Source: https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#google-analytics

**Comment by blogtutor** [comment]
Thanks Mike. We actually have a number of other exclusions, and we're broadening "google-analytics/analytics.js" to just "google-analytics" since we recently saw on a clients' site some _very_ old GA code wasn't being excluded... ;) 

https://github.com/blogtutor/blog-tutor-support/issues/157
