### ISSUE TITLE
Mobile menu item is hidden

### ISSUE THREAD

**Issue by ecotechie** [blogtutor/blog-tutor-support#154]
Need to add an icon and allow it to stay visible while in mobile mode. Otherwise, the mobile menu is not usable.

**Comment by blogtutor** [comment]
Looks like we might need to add a `display: inline-block !important` to the CSS.  

...that's what Yoast is doing -- though they're also using an icon instead of text.  Ideally we should have an icon there instead of text, on mobile...

**Comment by ecotechie** [comment]
Better if we link to the commit that close tickets rather than the release... 34cc13678e85c80cc39a202a2e06bb4ee6e53618
