### ISSUE TITLE
Shortpixel Plugin - Prevent Users from Generating Next Generating Images

### ISSUE THREAD

**Issue by karinclimber** [blogtutor/blog-tutor-support#158]
This morning there was a ticket where images were broken on a site - a client tried to regenerate her thumbnails including the AVIF and webp versions of the images (which charge an additional credit per image.) The site was trying to display AVIFs which were not working of course... Can we prevent clients from doing this with the plugin?

<img width="1078" alt="Screen Shot 2021-08-13 at 10 00 09 AM" src="https://user-images.githubusercontent.com/25188477/129369064-9eced4c7-7ea7-42e3-8e0d-449b65994c3a.png">

**Comment by ecotechie** [comment]
@blogtutor we could hide these two.

**Comment by ecotechie** [comment]
New branch created:
https://github.com/blogtutor/blog-tutor-support/tree/shortpixel-override

**Comment by ecotechie** [comment]
Fixed by hiding ShortPixel settings page in version 1.3
