### ISSUE TITLE
Help Tab not always displaying on dashboard home page

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#16]
Seems to be an intermittent issue. The main javascript is loading fine (clicking "Get Help" in the menu will open the knowledge base). 

But, the tab also shows up if you open the KB (via the "Get Help" menu link), and then close it (without reloading the page)...as soon as it's closed, the Help Tab appears.

**Comment by ecotechie** [comment]
Setting in Support Hero was blocking tab from showing.
