### ISSUE TITLE
Our "Need Help?" tab is showing up in the Widget Block Editor

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#161]
Boo!

![image](https://user-images.githubusercontent.com/24479276/130679021-0bdfa0e4-a985-4eb0-9698-f34c2658cdd9.png)

**Comment by ecotechie** [comment]
https://github.com/blogtutor/blog-tutor-support/commit/10f25afe999d106801de8a77d2fc7ab06956e60f Closes this ticket.
