### ISSUE TITLE
Add "flywheelsites" to Cloudflare cache purge exclusion list

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#169]
Please add `flywheelsites` to the list.

https://github.com/blogtutor/blog-tutor-support/blob/c1341ba0fdbf7d4f3fde00afd868bb0eb87dfdcb/includes/class-support-helpers.php#L252-L262

**Comment by blogtutor** [comment]
Ooh, I just found this list on the FlyingPress site - maybe we include (some of?) these all as well...

```
localhost
*.dev
*.local
*.test
dev.*
staging*
test.*
*.closte.com
*.runcloud.link
*.kinsta.cloud
*.cloudwaysapp.com
*.pantheonsite.io
*.sg-host.com
*.onrocket.site
*.pressdns.com
*.wpengine.com
*.bigscoots-staging.com
*.e.wpstage.net
```

https://docs.flying-press.com/account/staging-sites

**Comment by ecotechie** [comment]
@blogtutor are these in the domain? Or do we want to exclude them as strings in the URL?

> Let's also add:
> 
> ```
> wc_user_membership
> shop_subscription
> ```
> 
> (These came up on decadentdetox/skinn60, and patternsforpirates, respectively.)

**Comment by blogtutor** [comment]
Strings in the URL. Here's an example:

```www.thedecadentdetox.com
NerdPress_Cloudflare_Client::handle_comment_cache_transition approved delete
"{  "result": null,  "success": false,  "errors": [    {      "code": 1123,      "message": "URI Query string was provided in prefix www.thedecadentdetox.com/?post_type=wc_user_membership\u0026amp;p=41779. Query strings must not be provided."    },    {      "code": 1016,      "message": "One or more cache purge errors"    }  ],  "messages": []}"
CF-Ray: "69ec7eec68552c64-ORD"
User: tess (Tess Masters)
URL: https://www.thedecadentdetox.com/?post_type=wc_user_membership&p=41779
Cleared: "www.thedecadentdetox.com/?post_type=wc_user_membership&p=41779"```

**Comment by ecotechie** [comment]
This case is dealt with by using the NERDPRESS_CACHE_CLEAR_BYPASS. But in it's current iteration, it only takes a single string.

**Comment by ecotechie** [comment]
Yup, cleaning up as I add the other feature...
