### ISSUE TITLE
Disable WordPress 6.1 automatic WebP Generation

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#178]
6.0 is slated for release on May 24, 2022.  So we need to get this in place before then!

https://make.wordpress.org/core/2022/03/28/enabling-webp-by-default/

https://core.trac.wordpress.org/ticket/55443

**Comment by blogtutor** [comment]
It's now slated for 6.1 and sadly that looks definitive, scheduled for a November 1 release.

Based on the content of [this plugin](https://wordpress.org/plugins/disable-webp-by-default/#developers), this looks like the filter we'll need to add to ours:

```
add_filter( 'wp_upload_image_mime_transforms', '__return_empty_array' );
```

Should we also add an option in our settings to disable this, if a client should actually want WebP images generated?

**Comment by ecotechie** [comment]
For newer sites maybe? Not sure where all this will end up...

**Comment by CNoemi94** [comment]
The proposal didn't go through: https://make.wordpress.org/core/2022/03/28/enabling-webp-by-default/

Do we want to close this?

**Comment by blogtutor** [comment]
Yeah I think at this point we can safely close. Can always reopen this if they decide to try again.
