### ISSUE TITLE
Server IP or domain as secondary key for server changes

### ISSUE THREAD

**Issue by ecotechie** [blogtutor/blog-tutor-support#180]
Maybe we send IP or domain base64 encoded to the relay server as a check against site, domain, host changes?

**Comment by blogtutor** [comment]
So we add a field in the support settings where we set the domain name (and then base64 encode it to avoid staging site search/replace issues) - and check against that... This should help keep staging site from sending home data.

**Comment by blogtutor** [comment]
Rotating API key as part of our hosting change checklist will solve this.
