### ISSUE TITLE
Gray out Cloudflare options if site is not on CFE

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#183]
If the "Firewall" selection is not "Cloudflare Enterprise" we should gray out the "Cloudflare DNS Zone" and "Cloudflare API Token" options -- to make it clear they are not applicable.

We don't want to fully hide them, though; better to keep them visible so we can see what they're set to regardless. Something like this:(I just set `opacity: 40%` for this mockup):

![image](https://user-images.githubusercontent.com/24479276/169144852-622f996b-d986-436d-a1e2-ad9c3ad0010a.png)

**Comment by blogtutor** [comment]
Needs some JS so that clicking on the radio buttons activates/hides the settings without needing a save/page load.

**Comment by ecotechie** [comment]
Do we really care about it needing to be disabled immediately vs. after saving changes? It's done and working now, or I can re-write it to use JS.
