### ISSUE TITLE
Remove language file & clean up accordingly

### ISSUE THREAD

**Issue by ecotechie** [blogtutor/blog-tutor-support#19]
This is named incorrectly.

**Comment by ecotechie** [comment]
@blogtutor This is a little complicated. Not exactly sure what to do with this file. Except rename some things...

**Comment by blogtutor** [comment]
@ecotechie  Does this actually matter?  If so, can you please explain a bit further what this is about?

**Comment by blogtutor** [comment]
We're not translating, nor using the support-hero.pot file.  Let's remove it and remove any direct references to it... 

Our plugin should continue to support future translations, though - so don't remove any "translatable" features.
