### ISSUE TITLE
Move Github Updater into a separate class

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#210]
~75 of our sites don't show updates available when we update the NerdPress Support plugin.

Bill was kind enough to look into it and has some suggestions on how to fix:
https://nerd-press.slack.com/archives/C7N19NT6X/p1664390862830799

**Comment by ecotechie** [comment]
I wonder if this would be a better approach. Though I'm finding it hard to find clear documentation on this filter:

**Comment by ecotechie** [comment]
https://github.com/AppSys/rentman-plugin/blob/master/rentman.php#L528

**Comment by ecotechie** [comment]
https://github.com/janw-me/update-tutorial/blob/main/class-external-updater.php#L56

**Comment by ecotechie** [comment]
https://github.com/deltafactory/wordpress-self-hosted-updating-plugin/blob/master/wordpress-self-hosted-updating-plugin.php#L27

**Comment by ecotechie** [comment]
These are possible options to replicate in our code...
