### ISSUE TITLE
Hide Broken Link Checker's Source "Trash" Link

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#211]
The "Trash" link in the "Source" column of Broken Link Checker is hella dangerous... we think people may be accidentally deleting content without realizing it. Simple solution is to hide the "trash" link.

Let's load this on all the BLC pages (including filters of this page)...it will also remove the "Move sources to Trash" from the Bulk drop-down as well.

https://www.nerdpress.net/wp-admin/tools.php?page=view-broken-links
```
#blc-links .column-used-in .trash, #blc-bulk-action-form option[value="bulk-trash-sources"] {
    display: none;
}
```

**Comment by ecotechie** [comment]
@blogtutor I assume we want an option to load this or not? Or do you want to just blanket hide these links?

**Comment by blogtutor** [comment]
I can't see any reason why any of our clients would ever need these links. Let's just hide 'em.  If we find that's an issue we can add an option later. Thanks! :)

**Comment by blogtutor** [comment]
I think we need to adjust... it seems they've changed the URL so we're targeting the wrong things now.

![image](https://github.com/blogtutor/blog-tutor-support/assets/24479276/cdff0a91-ff21-415b-8eda-8687e014ec75)

Now it's `blc_local`
`https://www.thelittleepicurean.com/wp-admin/admin.php?page=blc_local&filter_id=f1`
