### ISSUE TITLE
Broken Link Checker CSS Hides "Unlink" Link.

### ISSUE THREAD

**Issue by halounsbury** [blogtutor/blog-tutor-support#217]
The Broken Link Checker CSS added in plugin version 1.5.0 was intended to hide the "Trash" link but it is also hiding the "Unlink" link, which is a useful link to have.

So, we need to adjust the CSS to unhide the "Unlink" link.

[](https://secure.helpscout.net/conversation/2057735537/117809/)

**Comment by ecotechie** [comment]
There was some kind of use for this. I think there were other links that showed up for comments or posts that were addressed by 
[this line](https://github.com/blogtutor/blog-tutor-support/blob/main/includes/class-support-overrides.php#L47).

But I'll need to look into this next week.
