### ISSUE TITLE
Add "Clear this page from Cloudproxy cache" to front-end menu

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#22]
Similar to how WP Rocket has "Purge this URL".

API v1 method (I think):

`https://waf.sucuri.net/api?k=API_KEY&s=API_SECRET&a=clearcache&file=FILE_PATH`

API v2 method:
```
curl 'https://waf.sucuri.net/api?v2' \

--data 'k=API_KEY' \

--data 's=API_SECRET' \

--data 'a=clear_cache' \

--data 'file=FILE_PATH'
```

**Comment by ecotechie** [comment]
Needs to only show on the front end.
Change link to "Clear this page from Cloudproxy"
