### ISSUE TITLE
Use helper function for plugin path

### ISSUE THREAD

**Issue by ecotechie** [blogtutor/blog-tutor-support#222]
In some places we've hardcoded the path to files. Let's use NerdPress::$plugin_dir_url instead.

So go from this:
`<img src="<?php echo esc_url( $site_url ); ?>/wp-content/plugins/blog-tutor-support/includes/images/nerdpress-icon-250x250.png" style="max-width:45px;vertical-align:middle;">`

To this:
`<img src="<?php echo esc_url( NerdPress::$plugin_dir_url .  'includes/images/nerdpress-icon-250x250.png' ); ?>" style="max-width:45px;vertical-align:middle;">`

**Comment by blogtutor** [comment]
Closed with #254  and  2.0.1 release
