### ISSUE TITLE
Fatal Error on WP Engine Hosting - Division by Zero

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#228]
After allweeat.com had a new theme launched, HTML pages were choking. Turns out it's only for NerdPress users. On PHP 8.0 on production we couldn't get an error message, but we set staging to 7.4 and got this error.

![image](https://user-images.githubusercontent.com/24479276/212796447-e32b0b2a-967c-440f-bb6d-1d0f9034a087.png)

**Comment by mikezielonka** [comment]
Thank you all! 💪
