### ISSUE TITLE
Change location of "Need Help?" tab (or hide it) on a per-site basis

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#24]
"Need Help?" tab conflicts with "Publish" button in editor when in 1-column mode.

https://secure.helpscout.net/conversation/727627942/7663?folderId=2016673

Perhaps we can just add a simple toggle in the plugin settings to hide the help tab -- keeping it active in the menu. This way for clients who request it, we can at least give them a workaround?

**Comment by ecotechie** [comment]
Added on 480187b760a28c9b06bdc7c7ffae9d2033915ada
