### ISSUE TITLE
PHP 8.2 Deprecation Notice from github-updater.php

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#247]
Just saw this on my test site on Cloudways that's running PHP 8.2.

`[14-Apr-2023 13:45:12 UTC] PHP Deprecated:  Optional parameter $default declared before required parameter $args is implicitly treated as a required parameter in /home/(redacted)/cqnzbbyvbw/public_html/wp-content/plugins/blog-tutor-support/github-updater.php on line 96`

**Comment by blogtutor** [comment]
@ecotechie Skylar just ran into this on a staging server and called it out... Let's get a fix for this into the next release?

I think it may be deprecated for both 8.1 and 8.2, but not sure.

**Comment by halounsbury** [comment]
This also shows a warning on PHP 7.4. Found this on a client site the other day on that version. (7.4.33)

**Comment by blogtutor** [comment]
Closed with Release 2.1
