### ISSUE TITLE
Two undefined array indexes

### ISSUE THREAD

**Issue by ecotechie** [blogtutor/blog-tutor-support#250]
[admin_notice](https://github.com/blogtutor/blog-tutor-support/blob/main/includes/class-support-snapshot.php#L138) and [np_relay_server_url](https://github.com/blogtutor/blog-tutor-support/blob/main/includes/class-support-helpers.php#L414) are bloating up the debug logs...

`PHP Notice:  Undefined index: admin_notice in /home/nginx/domains/domain.com/public/wp-content/plugins/blog-tutor-support/includes/class-support-snapshot.php on line 138
[20-Apr-2023 04:36:24 UTC] PHP Notice:  Undefined index: np_relay_server_url in /home/nginx/domains/domain.com/public/wp-content/plugins/blog-tutor-support/includes/class-support-helpers.php on line 414`

We should look into using the [null-coalescing](https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce) operator or [ternary](https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.ternary) operator for these.

**Comment by blogtutor** [comment]
@ecotechie Is this still an issue?

**Comment by ecotechie** [comment]
Already addressed.
