### ISSUE TITLE
Rearrange Settings Page Layout

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#251]
We should flip the layout of options on the main settings page, so the most used features are at the top instead of the bottom.

Firewall/Cloudflare settings and Relay API key should be front and center!

We should also add a "Save Changes" button at the top (can keep the one at the bottom as well, if we want?).

**Comment by CNoemi94** [comment]
I think we can close this. > https://github.com/blogtutor/blog-tutor-support/pull/300
