### ISSUE TITLE
Notes field needs linebreaks

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#262]
Can we find a way for the notes field to respect and display linebreaks?

**Comment by blogtutor** [comment]
Need to see how this impacts display on the relay server as well.

**Comment by CNoemi94** [comment]
From Sergio: "This is kind of an gateway into rewriting a bunch of code, because we have three (I think) ways to do admin notices in the plugin... It would be nice to only have one. But that's a bigger project and with WordPress having an eye to change the way admin notices are done."

**Comment by blogtutor** [comment]
I'm going to close this.  Longer-term, any notes are going to be stored and/or synced with the relay server.. so we don't need to spend any time adding linebreaks to the current implementation.
