### ISSUE TITLE
Send alerts to us for various diagnostic issues

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#27]
It would be great to have the plugin scan for various issues on a regular schedule (maybe once/day?) and send us an email notification if something isn't quite right.

Some initial ideas:

- Low disk space
- High 15-minute load average
- PHP version is <7.2
- Any of our support plugins are uninstalled
- Sucuri Firewall API key or Plugin API key is missing

We probably will need to have options in the settings page to disable/override individual notifications (so we don't end up spamming ourselves).

When we build this it should be done with the ability to easily add new notifications, so let's keep this in mind as we're setting it up.

**Comment by blogtutor** [comment]
Considering that many hosts aren't giving us good info for disk space or load average, perhaps we shouldn't include those, at least not at first.

And we have a TON of clients on PHP 7.0, so that could trigger a heck of a lot of emails...

**Comment by blogtutor** [comment]
Also, we need to have a way to disable individual alerts. Checkboxes in the settings page...

**Comment by tylerdigital** [comment]
What are the "our support plugins" that need to be checked for?

Sounds like initially this would just be checking PHP version, support plugins installed & activated, and Sucuri API keys?

Which email address should it send to for notifications?

**Comment by blogtutor** [comment]
Hi!  

**For the various plugins**, I think we should check for these to be active:

- Sucuri Security
- WP Rocket
- UpdraftPlus Premium
- NerdPress Remote Management (This is the ManageWP "Worker" plugin with whitelabeling)

**I do think we should include free disk space as well,** since most sites will give us that info correctly...as long as we have the ability to disable that easily in our settings page, per site.  We do run into sites (especially on Cloudways hosting) where they sometimes run out of space, so this would be helpful to have handy.  

I think that a good way to deal with the minimum amount of disk space (e.g., how much free space is actually available) that would trigger a warning would be ~110% of the total Uploads folder size. But, I would also love to be able to manually override that, as well.  So maybe there could be a field where we could enter the min amount of GB free for that site?

**Notifications should go to alerts@nerdpress.net.**

**Comment by blogtutor** [comment]
I just had an idea while I was in the shower. Perhaps instead of sending an email notification, we should just send a Webhook to Zapier.  It's a very simple way to push any data, and then we can have Zapier do whatever we want (send an email, log in a Google Spreadsheet, post on Slack, flash my office lights three times...).  

This would likely be faster to set up, be far more flexible in the future, and can also then trigger _multiple_ actions.  And, it doesn't rely on the website to be able to successfully send mail (which a lot of hosts block).

Thoughts?

**Comment by blogtutor** [comment]
Closing with 2.0 release/relay server launch!
