### ISSUE TITLE
current_user_can should reference capability, not role

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#282]
https://github.com/blogtutor/blog-tutor-support/blob/adcf412e0a88cf3a98737f399beb35b7297657bc/includes/class-support-widget.php#L18

Pretty sure this:

`current_user_can( 'editor' ) || current_user_can( 'administrator' )`

Should be changed to this:

`current_user_can( 'edit_others_posts' )`

**Comment by CNoemi94** [comment]
Agreed! The function takes capabilities not user roles: https://developer.wordpress.org/reference/functions/current_user_can/

**Comment by blogtutor** [comment]
We fixed some of these already, but there's still one left...

https://github.com/blogtutor/blog-tutor-support/blob/2bb1f10c04451a05ef85b8fc3ff692b42d7186e9/includes/class-support-helpers.php#L96

**Comment by CNoemi94** [comment]
@blogtutor  Updated the last function call
