### ISSUE TITLE
Add dashboard alert/message for our WP Rocket Delay JS exclusions

### ISSUE THREAD

**Issue by halounsbury** [blogtutor/blog-tutor-support#287]
There is confusion about the hidden WP Rocket Delay JavaScript "hidden" exclusions that we add via the plugin. Third parties not aware of our exclusions will tell clients that scripts are not being excluded and are causing issues when they are being excluded. 

So, it would be great if we could add some kind of WP dashboard alert, preferably on the WP Rocket settings page, explaining clearly and concisely which scripts we automatically exclude from WP Rocket Delay JS.

**Comment by blogtutor** [comment]
@CNoemi94 Would you up for tackling this?  We'd want an "Admin Notice" to show on only the WP Rocket settings pages.  Specific language TBD,..

**Comment by CNoemi94** [comment]
@blogtutor Sure thing!

Do we want this notice to be seen by all admin users since they have access to the WP Rocket settings?

**Comment by blogtutor** [comment]
I'd say that anyone who can see the rocket settings should see this... 

Maybe it should only be on the specific rocket page where it's applied, though.  I think we're really only talking about the File Optimization page, right?

`/wp-admin/options-general.php?page=wprocket#file_optimization`

Just FYI, these are the exclusions we add:
https://github.com/blogtutor/blog-tutor-support/blob/2bb1f10c04451a05ef85b8fc3ff692b42d7186e9/includes/class-support-overrides.php#L117

Note, I think we're only adding them to the Delay JS...not the Defer JS... so I think whatever language we craft should be accurate for that. @halounsbury we don't need others for JS Deferral, do we?

**Comment by halounsbury** [comment]
Should be for Delay only, yes. We don't do any automatic exclusions to Defer.

**Comment by feastdesignco** [comment]
@ecotechie enqueue into the admin scripts:
```
(function($){

     // Content to show before WPR excludes.
     $('.wpr-field #exclude_defer_js').before('<div style="display:block;">Instructions here!</div>');

})(jQuery);
```

![image](https://github.com/blogtutor/blog-tutor-support/assets/5629719/f38ed468-4384-448a-a3ff-61f6f5344447)

**Comment by blogtutor** [comment]
How about this copy?

**Heyo! NerdPress automatically adds exclusions here for Mediavine, Raptive (Adthrive), Google Analytics & Tag Manager, Slickstream, Nutrifox, Flodesk, ConvertPro, ConvertKit, and Hubbub (formerly Grow Social).  No need to add those here. 😎**

**Comment by halounsbury** [comment]
> How about this copy?
> 
> **Heyo! NerdPress automatically adds exclusions here for Mediavine, Raptive (Adthrive), Google Analytics & Tag Manager, Slickstream, Nutrifox, Flodesk, ConvertPro, ConvertKit, and Hubbub (formerly Grow Social). No need to add those here. 😎**

Looks good!
