### ISSUE TITLE
Add SheMedia scripts to WP Rocket Delay JS exclusions

### ISSUE THREAD

**Issue by halounsbury** [blogtutor/blog-tutor-support#295]
We should add WP Rocket Delay JS exclusions for SheMedia/BlogHer scripts as we have for Raptive and Mediavine.

Attached are some example scripts and "keywords" recommended by their support

**Comment by halounsbury** [comment]
![image](https://github.com/blogtutor/blog-tutor-support/assets/55807221/da7f705f-5453-4d36-ad17-23095696f03c)

**Comment by halounsbury** [comment]
This will also mean updating our WP Rocket alert in the WP Admin dashboard to include SheMedia/BlogHer to that list.

**Comment by CNoemi94** [comment]
@halounsbury is there a reason for the exclusions to be very specific? 

Do you think adding the following three lines would work?

- "shemedia"
- "blogherads"
- "sheknows-infuse.js"

**Comment by halounsbury** [comment]
@CNoemi94 Yeah, it's best to keep them just specific enough but not too broad that we have to add a lot of them.

I think these three should do the trick perfectly. Thanks!
