### ISSUE TITLE
Move JS notice to under WP Rocket Delay JS

### ISSUE THREAD

**Issue by CNoemi94** [blogtutor/blog-tutor-support#301]
The exclusions are done for WP Rocket Delay Javascript and not 'deferred' so please move the notice to reflect that.

**Comment by ecotechie** [comment]
@CNoemi94 would we benefit from some kind of formatting so the notice stands out more? Something like this ish...
![image](https://github.com/blogtutor/blog-tutor-support/assets/11607383/b6fd0aa1-2ab5-4a7d-9a4b-3084e12b1996)

**Comment by blogtutor** [comment]
Oooh, I do like the branded/purple background!  I was also thinking it didn't stand out quite enough, but didn't really have the headspace to come up with a solution.

https://brand.nerdpress.net/#Brand%20Colors

**Comment by CNoemi94** [comment]
Something like this:
![image](https://github.com/blogtutor/blog-tutor-support/assets/26862514/ec80e39e-b569-43be-ae5b-1c0449405422)


Had to make it bold so it's legible.
