### ISSUE TITLE
Remove WPRM from WP Rocket Delay JavaScript exclusions

### ISSUE THREAD

**Issue by halounsbury** [blogtutor/blog-tutor-support#306]
We want to remove the WP Recipe Maker scripts from being automatically excluded from the WP Rocket Delay JavaScript feature by the plugin hard-coded exclusions. This can potentially help improve INP and CLS on sites.

**Comment by mikezielonka** [comment]
THANK YOU CUZ THIS WOULD DRIVE ME NUTS.

**Comment by halounsbury** [comment]
WE'RE SO GLAD THIS WILL NO LONGER DRIVE YOU NUTS! @mikezielonka
