### ISSUE TITLE
Disk space & memory usage graphs not displaying on settings page

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#31]
Not displaying the graphs correctly on some sites. Examples include: lavoice.org, latinofoodie.com

**Comment by blogtutor** [comment]
Also, the memory usage is showing 100% usage on both these sites, which doesn't seem right...

**Comment by blogtutor** [comment]
LA voice is trying to load the stylesheet at this address:

https://www.lavoice.org/wp-content/plugins/css/html-serverinfo-field-style.css

It should be this:

https://www.lavoice.org/wp-content/plugins/blog-tutor-support/includes/css/html-serverinfo-field-style.css

**Comment by blogtutor** [comment]
Let's go with the super-simple solution on this for now.  Ditch the external stylesheet, and just hardcode the CSS into the page.

**Comment by ecotechie** [comment]
Fixed by entering the path in a more "hard coded" way... It's working. Kicking the can.
