### ISSUE TITLE
Sucuri Firewall automatic allowlist message blocks the WP Search

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#310]
At Tastemaker, Sarah from Sustainable Cooks told me that she finds the "You're IP has been automatically added..." message to be very annoying.  Specifically, it blocks the "Search" feature and that's what she always wants to use right away.

Maybe we can adjust so it's smaller and centered? And maybe also give it a "close" X in the corner? (I know it goes away after a few seconds, but still.)

![image](https://github.com/blogtutor/blog-tutor-support/assets/24479276/dd226793-41bb-4366-ab9b-87ddeb2f8103)

**Comment by blogtutor** [comment]
To get this box to show up, the site must be on the Sucuri Firewall, have the API key correctly configured, and the user must be a non-NerdPress Administrator.

We can test on lizthechef.com.

**Comment by ecotechie** [comment]
I think this is the place to look:
https://github.com/blogtutor/blog-tutor-support/blob/main/includes/js/bt-allowlist.js#L40
