### ISSUE TITLE
Undefined index: np_relay_server_url

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#317]
Kari just reported this on jeanniestriedandtruerecipes.com -- apparently it started March 29, so probably with NP Support 2.3.

`[15-Apr-2024 16:36:23 UTC] PHP Notice:  Undefined index: np_relay_server_url in /home/nginx/domains/jeanniestriedandtruerecipes.com/public/wp-content/plugins/blog-tutor-support/includes/class-support-helpers.php on line 414`

**Comment by ecotechie** [comment]
@jchristopher I'm guessing I can just add a ! empty() as you did?

**Comment by jchristopher** [comment]
That should do it! 👍
