### ISSUE TITLE
Add inactive themes site data

### ISSUE THREAD

**Issue by TinaCollier** [blogtutor/blog-tutor-support#319]
Hi (@1337rout),

If possible, can we add inactive themes to the data included for each site?

Currently, we can see the active theme for the site, but these are often child themes. If I wanted to find all of the Astra themes, I only get results that show sites using a theme named Astra.

If a site is using a Child Theme of Astra with an alternate name, then this site is not returned when filtering for Astra themes. 

Summary: Please include inactive themes for sites

**Comment by 1337rout** [comment]
Hi, @TinaCollier! I think if we got the parent theme information and made a filter for that, you could get what you are wanting. I am assuming you just want to know all themes that are using Astra, Genesis, etc if that name is in the child theme's name or not.
Am I correct in that assumption?

**Comment by blogtutor** [comment]
See also Heather's request to add Theme Authors. https://github.com/blogtutor/np-dashboard/issues/311

**Comment by TinaCollier** [comment]
Hi @1337rout Parent theme information would be great.

Currently, we can search for active theme using version. Since many Child Themes are renamed, we can't see what their parent theme is.

It would be nice to be able to see all inactive themes as well. We can see all installed plugins, both active and inactive. Can we have the same for themes?

**Comment by blogtutor** [comment]
> @blogtutor I get a 404 when I try to follow that link [blogtutor/np-dashboard#311](https://github.com/blogtutor/np-dashboard/issues/311)

just added you to the np-dashboard repo
