### ISSUE TITLE
Add Back Some WPRM Exclusions for WP Rocket Delay JS

### ISSUE THREAD

**Issue by halounsbury** [blogtutor/blog-tutor-support#324]
Eh, I hate to say this but I think we should add back the WP Rocket Delay JS exclusions for some of the WPRM scripts but be more specific this time.

On some sites, not excluding these can contribute to the JTR double-click issue. Usually it's in combo with other scripts but probably easier to exclude them again and the gains we got on INP probably weren't worth it.

Here's what I'd specifically like to exclude:

`/wp-content/plugins/wp-recipe-maker-premium/dist/public-pro.js
/wp-content/plugins/wp-recipe-maker-premium/dist/public-elite.js
/wp-content/plugins/wp-recipe-maker/dist/public-modern.js`

**Comment by blogtutor** [comment]
Turns out @halounsbury wanted this only for WP Rocket, not for Perfmatters too.

This PR addresses that:
https://github.com/blogtutor/blog-tutor-support/pull/327
