### ISSUE TITLE
Links to support page don't work properly on latinofoodie

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#33]
The links in the admin bar go to:
http://www.latinofoodie.com/wp-admin/options-general.php?page=nerdpress-support

But the correct page is:
http://www.latinofoodie.com/pages/wp-admin/options-general.php?page=nerdpress-support

We may need to generate the link from the WordPress Address, not the Site Address, from the settings?

![image](https://user-images.githubusercontent.com/24479276/51432309-542c5700-1bea-11e9-8db9-b53557186ab3.png)

**Comment by ecotechie** [comment]
Used get_site_url() to fix.

**Comment by blogtutor** [comment]
I just uploaded the current version to latinofoodie.com and this change did not fix fully.

Note that the link in the drop-down menu is correct now (including the /pages/ in the URL). But the link when clicking on the Load & Free Disk still does not have it.

**Comment by blogtutor** [comment]
Tested in 0.5.1-beta.2. All good! Thanks sergio you da bomb.
