### ISSUE TITLE
Incorrectly says the Sucuri plugin is missing

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#34]
On latinofoodie.com, the drop-down menu says "The Sucuri Plugin is Missing" even though the latest version of the Sucuri plugin is installed.

This was an issue 0.4.3 as well, so it isn't a new issue from the most recent changes. (I installed older versions on this site to test.)

**Comment by blogtutor** [comment]
We should instead be using is_plugin_active() and is_plugin_inactive() ...  and then we can have three results:

- Sucuri is installed and active
- Sucuri is installed and inactive
- Sucuri is not installed

That way we can have different messages in the drop-down menu, or add an alert in the dashboard.

Note that if used on the front-end, the plugins.php file must be called first. See docs:

https://codex.wordpress.org/Function_Reference/is_plugin_active
https://codex.wordpress.org/Function_Reference/is_plugin_inactive

**Comment by blogtutor** [comment]
Another reason to change this -- the uploads folder can be set to an alternate location (outside of /wp-content/), so we shouldn't hardcode that location.

I think better to use the is_plugin_active / is_plugin_inactive, but as a quick fix for our existing code, perhaps we can `use wp_upload_dir()`.

https://developer.wordpress.org/reference/functions/wp_upload_dir/

**Comment by ecotechie** [comment]
17dfa3b95cd1941ae967b8eb3b74dbb1d88bf1ae

**Comment by blogtutor** [comment]
Fixed in 0.5.1 release.
