### ISSUE TITLE
Require is_nerdpress() to authenticate with Google Workspace via Cloudflare Access

### ISSUE THREAD

**Issue by 1337rout** [blogtutor/blog-tutor-support#349]
If a user is_nerdpress, send them to our custom page that is covered under Cloudflare access to setup everything we need to authenticate that user. 

See many this thread. 

https://nerd-press.slack.com/archives/C07FG3966JY/p1723824681640229

**Comment by blogtutor** [comment]
We've got this running in the new repo/2.5 beta, so I'm closing this one.
