### ISSUE TITLE
Remove hardcoded reference to /wp-content/uploads/ for getting Cloudproxy API Keys

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#37]
In admin-menu.php, we currently load the sucuri-settings.php file with a partially hardcoded location:

Line 30:
`$input_lines = file_get_contents( ABSPATH . '/wp-content/uploads/sucuri/sucuri-settings.php' );`

That should be changed so that if the Uploads folder is in a different location it will still work.

https://codex.wordpress.org/Function_Reference/get_home_path
https://developer.wordpress.org/reference/functions/wp_upload_dir/

**Comment by ecotechie** [comment]
Using only wp_upload_dir() works as expected and should account for sub folder installations.

**Comment by blogtutor** [comment]
Looks good to me!  :)
