### ISSUE TITLE
Update details not showing up

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#4]
When an update is available, clicking on "View details" opens the modal but it doesn't properly load any info.

![image](https://user-images.githubusercontent.com/24479276/43843964-87797036-9add-11e8-9ca0-2e08cfcbc982.png)

**Comment by ecotechie** [comment]
@blogtutor  Looks like we need to add a [readme.txt](https://wordpress.org/plugins/developers/#readme) file at the root of the plugin folder.

**Comment by blogtutor** [comment]
@ecotechie  Yes, please get this started.. If you could just put in a rough placeholder readme.txt file that'd be awesome. we can add changelog stuff to it later. :)

**Comment by ecotechie** [comment]
Not sure we can do this with self hosted plugins... I added the files to the dev site, but nothing happened.

**Comment by blogtutor** [comment]
@ecotechie Could you please take a fresh look at this and see if you can figure it out?  See how far you get with 1-2 hours of research & dev...

**Comment by blogtutor** [comment]
Works correctly now - Parses the Github Releases API response and adds to plugin details array.
