### ISSUE TITLE
Consider adding ability to disable Site Health Checks

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#40]
Now that Site Health Checks is part of core, we may start getting concerned emails from clients.  If we find that there are health checks that aren't applicable and should just be turned off, we may want to add the ability to do that in our plugin.  

https://wptavern.com/site-health-tool-manager-provides-a-convenient-way-to-disable-unnecessary-site-health-check-tests

**Comment by blogtutor** [comment]
So it's been 6+ months and I don't think this has actually been an issue.  Think we should just close it, @ecotechie ?

**Comment by ecotechie** [comment]
Yeah, close. Better to let the feature improve than to hide it. Since we have had not false/misleading warnings reported.
