### ISSUE TITLE
Add option to slow down WP Rocket Cache Preload

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#41]
Either set it up so that we just always slow the preload to 2 or 3 seconds (default is 0.5 seconds). OR, have an option to enable it in some way.

https://github.com/wp-media/wp-rocket-helpers/blob/master/preload/wp-rocket-custom-preload-intervals/wp-rocket-custom-preload-intervals.php

**Comment by blogtutor** [comment]
```namespace WP_Rocket\Helpers\preload\sitemap;
// Standard plugin security, keep this line in place.
defined( 'ABSPATH' ) or die();
// EDIT THIS TO DEFINE A CUSTOM PRELOAD INTERVAL IN SECONDS:
define( 'WPROCKETHELPERS_PRELOAD_INTERVAL_IN_SECONDS', 5 );
// STOP EDITING.
/**
 * Set the preload interval for WP Rocket in microseconds.
 *
 * @author Arun Basil Lal
 * @author Caspar Hübinger
 * @return integer Custom preload interval in microseconds
 */
function apply_preload_interval() {
	return absint( WPROCKETHELPERS_PRELOAD_INTERVAL_IN_SECONDS ) * 1000 * 1000; // microseconds
}
add_filter( 'pre_get_rocket_option_sitemap_preload_url_crawl', __NAMESPACE__ . '\apply_preload_interval' );```

**Comment by Dibbyo456** [comment]
`pre_get_rocket_option_sitemap_preload_url_crawl` filter is deprecated as of v3.3.6

**Comment by Dibbyo456** [comment]
I have no idea. I am on the same boat as you are. The filter hook probably removed couple of version ago.

If you do a string search in the plugin codes using `pre_get_rocket_option_sitemap_preload_url_crawl` you won't get any hit. That's how I know it's deprecated.

I [also tweeted them](https://twitter.com/iarijitbiswas/status/1166037946262151168) about it you can keep a track there too.

AFAIK, there is currently no way to filter the interval, looks like they have hardcoded it with **0.5 seconds**. Check `/wp-rocket/inc/classes/preload/class-full-process.php`, **Line 69**.

Their knowledge base is complete mess, everything is outdated and very confusing, same goes with the WP Rocket Helpers on Github. 😑

**Comment by blogtutor** [comment]
Haven't needed to do this in a long time, so I'm closing this. If we do need to slow down the preload on a client site in the future, we can just add a Code Snippet or their helper plugin instead.
