### ISSUE TITLE
Automatically whitelist admin users in Cloudproxy

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#42]
Develop a system so that all admin users will have their IP address added to the Cloudproxy whitelist automatically after successful login.

Some considerations:

- We don't want IP addresses permanently added, because public WiFi networks should get cleared after a certain time.
- Some users don't log out manually. At home they may also stay logged in indefinitely, so simply clearing the IP from the whitelist after a set time will cause problems.

**Comment by tylerdigital** [comment]
I've got a PR ready for this but realized that I'm not on the repo. Can you add me as a user? `tylerdigital`

**Comment by blogtutor** [comment]
Yay! Invite sent. :)

**Comment by tylerdigital** [comment]
https://github.com/blogtutor/blog-tutor-support/pull/45

**Comment by blogtutor** [comment]
I just tested the API v1 Whitelisting, adding the `&duration=` variable, and it failed because my IP address was already whitelisted.  So we _do_ need to use API v2... which means we either need a different technique to make the javascript ajax request (since the menu option is using v1), or we need to change the menu to also use v2.

If we do change the menu to use v2, then it's also going to be a good time to change that so it doesn't open a new tab, but instead reloads the page with a proper admin notice. Perhaps we should open a separate issue for that?

**Comment by blogtutor** [comment]
API v2 reference:

```
curl 'https://waf.sucuri.net/api?v2' \
--data 'k=API_KEY' \
--data 's=API_SECRET' \
--data 'a=whitelist_ip' \
--data 'ip=IP_ADDRESS' \
--data 'duration=(time in seconds)'
```
Or:

`https://waf.sucuri.net/api?v2&k=API_KEY&s=API_SECRET&a=whitelist_ip&duration=SECONDS`

It also appears that `a=whitelist` and `a=whitelist_ip` both work, and we should not specify the IP address, so it just uses the visitor's current address.

**Comment by blogtutor** [comment]
Some additional features from our Slack convo that we need to include:

- Storing the IP Address returned by Sucuri's response, as the IP that was just whitelisted. Of course, we'll still need a way to "know" the current IP address of the logged-in user, since that will gets checked on every pageload.
- Making sure Cloudproxy is actually set up before attempting to whitelist (can probably use the same logic that's in the menu, which checks for the existing of the API keys in the Sucuri plugin settings PHP file).
- Using API v2 to whitelist the IP address, with a duration of 24 hours (or 48 hours?)
- Changing the Whitelist link in the NerdPress Menu so it doesn't open a new page, but instead returns a proper WP Admin Dashboard notice. (Changing to API v2 may be better for this as well?)  
- Note, detecting if the API key is set in the Sucuri settings is not actually a great way to determine if Cloudproxy is actually being used... since the API key stays set, even if the DNS has been changed (switched over to Cloudflare, for example). This may not matter -- whitelisting and cache clearing won't cause any errors -- but it's not ideal.  It may be better if we find a more robust way to determine if Cloudproxy, Cloudflare, or no proxy, is set up?  But maybe that's for another day.
- Adding some error handling on the API response... Not sure what all the possible errors are, but an invalid API key is certainly one of them.

**Comment by blogtutor** [comment]
Turns out the duration variable only works on API v2. 

And, 86400 seconds (1 day) is the max it'll allow.

**Comment by blogtutor** [comment]
Completed with 0.6.0 release. 🎉🍾🥂
