### ISSUE TITLE
Add form to whitelist any IP address in the "Sucuri" Tab

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#43]
Add to new "Sucuri" settings tab.  Using regular HTML form to submit the API call and add any IP address.

Would be great to have some input validation to make sure it's a valid IP address.

**Comment by ecotechie** [comment]
May need a bit of cleaning up, but working fine :)
https://github.com/blogtutor/blog-tutor-support/compare/28fb687e55a1...98e0734af2db

**Comment by blogtutor** [comment]
Works great!  Released feature in 0.5.2.
