### ISSUE TITLE
Roll back for updates

### ISSUE THREAD

**Issue by ecotechie** [blogtutor/blog-tutor-support#49]
Implement a roll back for our user so we can quickly revert bad updates.

**Comment by blogtutor** [comment]
WP Time Capsule includes this feature.

**Comment by blogtutor** [comment]
@karinclimber Would it be useful for us to build a feature like this into our plugin?   When we created this issue I don't think we were using ManageWP, so maybe this is unnecessary now, or not worth adding?

**Comment by CNoemi94** [comment]
@blogtutor, do you think this is still relevant? I think we use [WP Rollback](https://wordpress.org/plugins/wp-rollback/) for this functionality now.
