### ISSUE TITLE
"Get Help" in menu needs to work on front end

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#5]
The Get Help admin menu link currently displays on the front end of the site, but it doesn't work because we don't load the Support Hero widget.  We need to load the widget and then add some javascript to then hide the "Get Help" tab at the bottom...once that's in place the existing link in the menu should work.

From Florian:
> There is actually a method available on our widget to do this, maybe it'll help you achieve your goal here. You can indeed call:
> window.supportHeroWidget.hideWidget()
> Which will hide the widget tab. And if you want to show it, there's this other method if you want to hide it by default and show it only when inserted in the Wordpress dashboard:
> window.supportHeroWidget.showWidget()
> 
> Both methods are available as soon as the widget is loaded, so you might want to check that window.supportHeroWidget exist before calling them.

**Comment by blogtutor** [comment]
Re-added the tab on the front end, but the javascript to hide isn't working. I'll contact Florian.

**Comment by ecotechie** [comment]
We could do this in CSS:
.blog #supporthero-button {display: none !important; }

Since the widget only gets loaded when somebody selects the tab or menu item, I don't think it will create any perf issues.

**Comment by blogtutor** [comment]
Yeah, if we don't hear back from Florian with a javascript fix, we'll go the CSS workaround hack on the front-end as well.  

The widget doesn't _open_ until somebody clicks, but the javascript is loaded either way.  But I guess that's going to be the case no matter what, so maybe doing the CSS solution is just fine anyway.

I'm guessing we'd want a different selector than `.blog`... and actually, since we know we're on the front-end, and therefore can insert this CSS only if we're on the front end, we don't need to be as specific with it...   just `#supporthero-button { display: none !important }` outta do the trick! 
      `

**Comment by blogtutor** [comment]
Fixed in 0.4.0, using CSS to hide tab on front end.
