### ISSUE TITLE
Add a setting for which proxy service should be enabled

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#54]
Add a radio button option on the settings page to indicate which firewall/proxy service _should_ be enabled on the site:

- Sucuri Firewall  <-- Selected by Default
- Cloudflare
- None

**Comment by blogtutor** [comment]
I want to get this option/setting in place as soon as possible... even if we don't do anything with it (yet). The sooner we have it in place, the sooner we can make sure sites have the correct info.

Please also make sure that the default setting ("Sucuri Firewall is enabled") will actually be stored in the database options table upon install/update of the plugin (so we don't have to explicitly save the setting to have this get stored in the db.)

**Comment by AndreyK92** [comment]
@blogtutor I deployed the change to the dev site. Please lmk what you think :)

**Comment by blogtutor** [comment]
@AndreyK92 That looks good to me!  Two questions:

1 - Does this automatically add the Sucuri Firewall setting into the database on update/activation? I just want to be sure that's enabled without having to go to the page and click Save Changes.

2 - Should we add an "Other" option as well? I don't know what the future will bring...though I suppose if there's a new firewall we/clients start using, we could add it as an option later (or just keep it on "None")?  Maybe we could label it "None/Other" but store it in the DB as "none" (or the equivalent), so we can add an "other" later?  

@ecotechie thoughts?

![image](https://user-images.githubusercontent.com/24479276/70733031-54c85300-1cbe-11ea-94d9-d8c284628e92.png)

**Comment by AndreyK92** [comment]
1) Yea, if no option found, it defaults to Sucuri Firewall option. However, since we (@blogtutor , @ecotechie can probably confirm) have a few people with Cloudflare, I would need to detect it somehow before the option defaults.

2) Other sounds good :)

**Comment by blogtutor** [comment]
@ecotechie asked what "should be enabled" means on the ticket.

My thinking is that if we know what service "should" be enabled, we'll be able to have the plugin notify us if something is misconfigured (e.g., if Sucuri should be enabled, but they changed hosts and moved to Cloudflare, we'll get a notice), and we can also have the plugin adjust things in the future to work better with the given proxy service.

We can auto-detect (such as checking the headers to see if Sucuri or Cloudfare included a response), but my thinking is that we should do _both_ things...that way if something should be a certain way, but isn't, we can take proactive steps to correct it.

**Comment by AndreyK92** [comment]
> We can auto-detect (such as checking the headers to see if Sucuri or Cloudfare included a response), but my thinking is that we should do **both things**

What's the second thing with auto-detect?

**Comment by ecotechie** [comment]
So this would be for:
1. Future reporting to us once #27 is closed.
2. Adjust "things" (not clear on what this means).
3. Decide what to display on the plugin menu.

Not clear on the benefit vs effort here.

**Comment by blogtutor** [comment]
> What's the second thing with auto-detect?

Sorry if that was unclear. There's just one thing to auto-detect -- which proxy is actually active.

My point is that we need two pieces of information:
1. Which proxy is _actually_ active, if any.
2. Which proxy _should be_ active, if any.

That will give us a few benefits. Some examples

1. We can take proactive action to fix it if they don't match up (e.g., the site is configured differently than expected or desired).
2. We can change functionality of the plugin, based on the desired configuration. For example, if the Sucuri Firewall isn't active, _and isn't supposed to be_ we can simply hide the Sucuri features from the client, and also disable auto-whitelisting. [keep in mind that just because a Firewall API key is set doesn't mean that the Firewall _should_ be active]

As for "Benefit vs. Effort" this seems to be rather low effort - at the moment, it's simply adding an option and saving it in the DB. The default will be appropriate for the vast majority of our clients.

Then, once we have that in place, we can apply logic in the code based on this, more reliably and more repeatable as we expand the plugin. I'm not sure where else that we'd want to use this yet, but the two benefits listed above are reason enough in my mind to do it now.

**Comment by ecotechie** [comment]
I'm onboard. Currently our way of checking if the Sucuri Firewall is active is just checking for the key in appropriate file. This should be more robust.

**Comment by AndreyK92** [comment]
What kind of response do we get when we send any request to Sucuri while the firewall is inactive? We might need a cron job here. Getting Sucuri's response is the most sure way to detect if it's active.

**Comment by blogtutor** [comment]
I think the API responds normally. There is a "status" that it keeps track of, but I've actually found that to be a bit flukey.. it doesn't always reflect the current status accurately.

I think the most reliable way for us to detect if it's active is if the HTTP_X_SUCURI_CLIENTIP header is set.

**Comment by blogtutor** [comment]
Let's not overthink this.  For the moment, all we need is a setting in the database, to tell us what "should" be enabled.

I also don't think we need to do any autodetection at install. What we can do is have all sites set to Sucuri for now, and then we can manually change those sites that aren't actually supposed to be using Sucuri. Heather has a list (from when we had to change API keys), and I have a list (from when the Sucuri outage happened in October).

**Comment by AndreyK92** [comment]
OK, should I push the changes to master?

**Comment by blogtutor** [comment]
> 1. Yea, if no option found, it defaults to Sucuri Firewall option. 

Before you push to master, just want to confirm: When you say "if no option is found, it defaults..." when does that happen?  I want to be sure that we save the option in the DB upon install/activation, or upon update... so that there's an option already stored, without going to the settings page to click "Save."

**Comment by AndreyK92** [comment]
The option is created if the option doesn't exist. So in any case of this option not existing it would automatically be created whether it's a plugin install, update etc.

**Comment by blogtutor** [comment]
Fabulous.  Push it!

![](https://i.giphy.com/media/ZJFmfvMutiQ0M/source.gif)
