### ISSUE TITLE
Build a custom dashboard and have all sites send data back to it

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#55]
Scot at Rumspeed does this, using Air Table as the main dashboard. He's been planning on building a SaaS product that makes this available to others, but I'm not sure the status. So it might be time we build our own.

This might be better suited for some things than the email notification system proposed in https://github.com/blogtutor/blog-tutor-support/issues/27

Some initial thoughts on data that would be great to have on a central dashboard:

- Active Plugins (with version numbers, highlighting any due for updates)
- Inactive Plugins 
- Missing or Inactive Plugins that should be there (Flagging our core plugins - Sucuri, WP Rocket, etc.)
- Perhaps highlighting common premium plugins with expired licenses?
- WP Core version
- PHP Version
- Free disk space
- Firewall status (which proxy _should_ be active, which _is_ active)
- Notes (syncing with current admin dashboard notes feature!)
- Uptime Robot status (pull from Uptime Robot's API)

And some other "Static" info:
- Client name(s) & contact Info
- Link to create new email in Help Scout
- Link to support history
- Link to Metorik customer page (showing order history)
- Support Level (SS, IP, ZM)

**Comment by AndreyK92** [comment]
Where would you like this dashboard to be accessed from i.e. how would you want to access it?

**Comment by blogtutor** [comment]
Forgot this one was here. Closing in favor of #85.
