### ISSUE TITLE
"Cache successfully cleared" notice is a bit too sticky

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#61]
So this is a little weird. I just went back to eatingrules.com/wp-admin/ (in a new tab, browsing directly to that URL), and at the top of the dashboard page is the "Sucuri Firewall is being cleared" admin notice.

I actually had this happen once or twice before -- after clearing the cache, page reloaded with the message. all good, until I browsed to another page and the message was still there. in that case, no biggie since I had just cleared the cache. But in this case, I hadn't touched anything in awhile, so the message is disconcerting.

Slack convo here:
https://nerd-press.slack.com/archives/C7N19NT6X/p1576021631055600

**Comment by AndreyK92** [comment]
I will use the wpdb options table instead of a php session to store if the previous page had the clear cache executed
