### ISSUE TITLE
Add "Clear local whitelist cache" button on Sucuri Settings Page

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#62]
In addition to displaying the current local IP whitelist (stored in the WP database), it would be nice to have a "Clear" button on the same page... This would make testing and troubleshooting a wee bit easier.

So, please add a button to remove the whitelisted IPs from the database, the same way it gets auto-cleared every 12 hours.  This should goon the "Sucuri Settings" plugin tab/page.

**Comment by AndreyK92** [comment]
Should we have clear for each individual IP or for the whole list?

**Comment by blogtutor** [comment]
I think we can just clear the whole list, right?  Anyone working on the site will be immediately whitelisted on their next pageview anyway, right?

Said another way: Do whatever's faster/easier. ;)

**Comment by AndreyK92** [comment]
Yea, let's do that then.
We also don't want to create a very bulky UI (too many options) :)

**Comment by AndreyK92** [comment]
We probably shouldn't display the button if the Sucuri's IP header isn't set. What do you think @blogtutor ?

**Comment by AndreyK92** [comment]
Currently the Sucuri's page is displayed if the Sucuri API is good

**Comment by blogtutor** [comment]
How about we put the display of the locally-cached IP address (and the clear button) on the Sucuri Tab in the NerdPress settings pages...  and then we don't display the tab at all if Sucuri isn't active.

The display of the Sucuri tab should be based on the option set in the main settings page (not if the header is set), so we can modify the options even if Sucuri isn't active.

**Comment by AndreyK92** [comment]
Good idea! I'll add a check for the option we just created
The option is already useful :wink:

**Comment by AndreyK92** [comment]
This is added too, please test :)
https://dev.blogtutor.com/wp-admin/options-general.php?page=nerdpress-support&tab=sucuri_settings

**Comment by blogtutor** [comment]
This is great!

Small label notes, just for clarity:

Please change the header to "Automatically Whitelisted IPs" (since this isn't the full list of whitelisted IPs). 

And then please change the button label to "Clear Local Whitelist Cache".

**Comment by AndreyK92** [comment]
Done! :rocket:

**Comment by blogtutor** [comment]
Woohoo! Commit to Master branch and close this one out...  :)

(I think when do you do the commit, if you say something like "Closes #62" it'll automatically close it.) 

https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by AndreyK92** [comment]
OK, there are a few issue I'm gonna close with the next commit. I wonder if listing them would also close all the cases at once :thinking:
