### ISSUE TITLE
Click-to-close menu drop-down after cache clear

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#63]
On the front end, we're forcing the menu drop-down to stay expanded after someone clicks "Clear cache"... so this way they'll see the "Please wait..." and response message in the menu.

After it shows "Success!" or "Error!", clicking anywhere else on the page (outside the drop-down, but not necessarily on a link) should close the menu and restore native/standard behavior for the menu. 

The Success/Error message should probably stay in the menu, so if they expand the menu again, they'll see the same message.

**Comment by AndreyK92** [comment]
This has been deployed to test on dev.blogtutor.com

**Comment by blogtutor** [comment]
Good morning!  I just tried this on dev.blogtutor.com, on the homepage. When I clicked "Clear Cache" the menu closed as soon as my mouse moved away... So now the menu isn't staying open like before.  ?

**Comment by AndreyK92** [comment]
Hm, tested it yesterday and it worked as I expected. Now it works as you describe.
The good version was probably cached when I tried it. Looking

**Comment by AndreyK92** [comment]
Just re-deployed the old version of the script (the one that wasn't "unhiding" the dropdown ) and the element is still being hidden on the mouseout event. Very strange!

**Comment by AndreyK92** [comment]
Just re-deployed the old version of the script (the one that wasn't "unhiding" the dropdown ) and the element is still being hidden on the mouseout event. Very strange!

**Comment by AndreyK92** [comment]
jQuery's off method just seems to have stopped working

**Comment by AndreyK92** [comment]
This was caused by the WordPress update. Adjusted and fixed.
