### ISSUE TITLE
Hide "Sucuri Settings" tab if Sucuri is not selected

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#64]
Please hide the "Sucuri Settings" tab completely if "Sucuri Firewall" is not the selected firewall option.

It looks like right now, if Sucuri is not selected, the tab is still there and then it says "Sucuri Firewall is disabled or Sucuri Firewall API Key is not found"...which isn't really accurate.

OR, if that's too complicated/time-consuming, please change the existing message to "Sucuri Firewall is not selected as the proxy." ..that'd be fine too. :)

**Comment by AndreyK92** [comment]
OK, I'm hiding the tab if Sucuri FW isn't enabled now. Try switching the option to something other than Sucuri  :)
