### ISSUE TITLE
Determine if it's on a production or staging site

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#65]
Clients often clone their sites to a staging server, and that causes some of our notification plugins (especially Sucuri) to start kicking out warnings to us. That gets quite annoying.

But if we deactivate the Sucuri plugin on staging sites, we run the risk of it being deactivated when clients push changes back to production (though most don't _actually_ do push/pull or other synchronization), so we wouldn't want Sucuri to get deactivated on production. With the future notifications of plugins being inactive (#27), we don't want that to happen.

I'm wondering if we can add an option to our settings page, for something like "Is this a staging site?" that will deactivate various alerts that we're going to be enabling.

But then, we also wouldn't want that feature to stay enabled if it gets pushed back to production.

Perhaps it could be different option -- something like, "If this is a staging site, enter the temporary domain here:" And then if there's a temp domain entered, it only actually takes effect if it matches the actual domain of the staging server?  (So entering something like "dev.eatingrules.com" in that box would enable the feature only on that domain.)  Not sure if the server can determine its own domain, though?

Let's brainstorm a good way to solve this, so it's robust for the future?

**Comment by AndreyK92** [comment]
> Not sure if the server can determine its own domain
Yes it can :) Domain name is extracted from the request header. So it would be available. Example: $_SERVER['HTTP_HOST']

Maybe we can just have an option - "Staging site url" and have a tooltip explaining why it's needed

**Comment by blogtutor** [comment]
But we won't always have a request header... I'm thinking about our future notifications system, for example, which will run based on a cron, not on a pageview. That's going to be running its own process locally, with no visitor hitting the server with a web browser.

Right?

**Comment by AndreyK92** [comment]
If a request header is absent we can use $_SERVER['SERVER_NAME'] which works in most cases but can be config dependent.

Are we talking about WP Cron jobs here? It yes, they're always triggered by a request

**Comment by blogtutor** [comment]
Ok, I'm going to leave it to you to figure out the most efficient and
reliable way of detecting the installation's domain.  :)

**Comment by blogtutor** [comment]
WP 5.5 will include a function to help with this:

![image](https://user-images.githubusercontent.com/24479276/89237468-19112f00-d5a8-11ea-92b2-81fefaab8a87.png)

**Comment by AndreyK92** [comment]
Hmm, I think this one is retrieves the environment string. Something like "production"/"development"/"staging".
Here are the docs: https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/

**Comment by blogtutor** [comment]
Per Bill Erickson:

```// Only run on production
if ( function_exists( 'wp_get_environment_type' ) && 'production' !== wp_get_environment_type() ) {
	return;
}
```

**Comment by blogtutor** [comment]
This is done with release 1.1.
