### ISSUE TITLE
Whitelist NerdPress team for 2 hours instead of 24

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#66]
Sucuri confirmed that API response times are a known issue.. they're working on APIv3, but there's no ETA at all. So I think it's safe to assume the slow response time for our IPs is going to remain an issue for awhile.

So...

1. If the user `is_nerdpress()`, whitelist the IP address for 12 hours instead of 24.
2. The notification/confirmation message popup should say 12 hours instead of 24.
3. It might also be helpful to show the API response time in the notification popup, if it's a quick/easy thing to add... but again, only for NerdPress team members.

**Comment by AndreyK92** [comment]
1) Done
2) Done
3) Done

Basically, I just created another option for the NerdPress members in the wpdb that acts the same as the other whitelist with it's own cron job. The alternative route was to add a flag for the whitelist ips but I opted not to in case compatibility issues that may arise from changing the option's datatype ( array => map).

**Comment by blogtutor** [comment]
1. - change the second cron to purge the nerdpress IP local cache every 2 hours.
2. - change the whitelist duration for nerdpress users to 2 hours
3. - add the nerdpress local IPs to the settings page
4. - add a button to manually purge the nerdpress ips

**Comment by blogtutor** [comment]
Change notification to "Response from Sucuri took..." (instead of "Request from Sucuri...")

**Comment by AndreyK92** [comment]
BTW, should we have two buttons for clearing IPs for nerdpress and regular people?
Pros: We won't clear out clients' IPs.
Cons: Increased complexity (room for bugs, confusion)

We can just clear all the ips with "Clear Local Whitelist Cache" button.

**Comment by blogtutor** [comment]
Let's have two buttons. That way we can clear ours without clients seeing the "you've been whitelisted again" notification.

**Comment by AndreyK92** [comment]
OK, this is ready to test on the dev site.

One question: should we separate the two lists on the setting page? My vote is yes but I left just a single list with all the WLed IPs (for both regular users and the NP peeps) for now.

**Comment by blogtutor** [comment]
Let's separate it out, otherwise it's not clear which IPs are being cleared by which button.

I also clicked "Clear Local Nerdpress Whitelist Cache" and it cleared your IP and mine...not just mine.

(Also, there's a capital P in NerdPress.)

**Comment by blogtutor** [comment]
I was curious to check on the cron scheduling, so I just installed WP Crontrol.  Looks like the NP local cache clear is still set to twice daily instead of every 2 hours.

![image](https://user-images.githubusercontent.com/24479276/71132986-fd3e5180-21ad-11ea-9696-b07fb76a8101.png)

**Comment by AndreyK92** [comment]
It's probably caused by it being initially scheduled "twice daily". Let me delete event and let's see what's gonna be scheduled

**Comment by AndreyK92** [comment]
OK, it changed to 2 hours now :blush:

**Comment by blogtutor** [comment]
Let's do 2 hours 15 minutes of whitelisting (keeping the cron job at every 2 hours), to avoid gaps in coverage.

**Comment by AndreyK92** [comment]
Changed :)
