### ISSUE TITLE
Refactor when "Clear Cache" link appears in menu

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#67]
The "Clear Sucuri Firewall Cache" and "Clear this page in Sucuri Firewall" links should only appear in the NerdPress menu when:

( 1. We actually have a firewall API key (in the sucuri-settings.php file) )
AND
( 2A. "Sucuri" is the firewall selected in the NerdPress settings, AND/OR
2B. The HTTP_X_SUCURI_CLIENTIP header is set. )

We should then also show "The Sucuri Plugin is inactive" and/or "The Sucuri plugin is missing!" in the menu separately, _above_ the clear cache link, if they are applicable.

**Comment by blogtutor** [comment]
@AndreyK92 I see you closed this and reopened it...did you actually implement any of these changes yet?

**Comment by blogtutor** [comment]
If not... I'll move this to 0.6.3  😎

**Comment by AndreyK92** [comment]
I put the wrong issue # in my commit message so it closed the case :(

**Comment by AndreyK92** [comment]
So in this case item 1 and item 2B should determine if the "Clear Cache" button should show? if item 1 and item 2B are set but item 2A isn't set, it should alert us, however we should still show the button.

Would the flag also affect the showing of the whitelist link for NP users?

**Comment by blogtutor** [comment]
Let's either show or hide _both_ menu items (clear cache/whitelist for NP users), since they're both for Sucuri.

And maybe let's not overthink this. How about we simplify it, to only show the menu items if (1) the firewall API key is set, AND (2) the sucuri header response exists.  

(So we don't need to incorporate the firewall setting in the plugin when determining whether or not to show the menu items.)

?

**Comment by blogtutor** [comment]
And then we'll take other action and/or show other things in the menu, if the firewall API key isn't set or the sucuri header doesn't exist (but only if Sucuri is selected in the settings).
