### ISSUE TITLE
Refactor dashboard notices to use WP Coding Standards

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#73]
Here's the URL structure that WP Rocket uses:

`https://dev.blogtutor.com/wp-admin/admin-post.php?action=purge_cache&type=all&_wp_http_referer=%2Fwp-admin%2Fplugins.php&_wpnonce=ec422a069d`

**Comment by blogtutor** [comment]
...and get rid of the dreaded `session_start()` once and for all! ;)

**Comment by blogtutor** [comment]
Found a little bug.. now if I change the firewall setting (say, from sucuri to cloudflare, or vice-versa), on the page reload, it will show the "Settings saved" message twice.

It first shows the message above and below the three tabs. Then as the page loads, it shifts and looks like this:

![image](https://user-images.githubusercontent.com/24479276/72029119-c7830a80-3239-11ea-85df-4c5d0ca12470.png)

**Comment by blogtutor** [comment]
And found another issue. If the Firewall API key is set -- but incorrect -- then we're not displaying any error message.  The page just reloads with no message. We need to have some kind of error message displayed in this case...

**Comment by blogtutor** [comment]
Actually, I'm not seeing ANY dashboard notice after clearing the cache (even with the correct firewall API key).  I'm guessing you're still working on it?

**Comment by AndreyK92** [comment]
>Actually, I'm not seeing ANY dashboard notice after clearing the cache (even with the correct firewall API key). I'm guessing you're still working on it?
Are you still experiencing the issue? I can't replicate the problem.

**Comment by AndreyK92** [comment]
> And found another issue. If the Firewall API key is set -- but incorrect -- then we're not displaying any error message

Yes. We should create a separate case for this one

**Comment by blogtutor** [comment]
> > Actually, I'm not seeing ANY dashboard notice after clearing the cache (even with the correct firewall API key). I'm guessing you're still working on it?
> 
> Are you still experiencing the issue? I can't replicate the problem.

Found the problem... the old .js files were still cached for me, so it was using the old query string variable to show the message.  It's working with the  `?np_clear_sucuri=true now.`

I moved the other two bugs I found to other tickets - so I'm closing this one!
