### ISSUE TITLE
Sanitize Sucuri API Response

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#75]
Don't save anything in the database unless it's actually an IP address!

Here's the weird API response that was causing "N"'s to be saved in the array (maybe for Null?). 

`{"status":0,"action":"whitelist_ip","messages":["Settings not found. Please try to logout\/login again."],"request_time":1578520312,"output":[],"verbose":1}`

**Comment by AndreyK92** [comment]
Yep, wordpress serializes NULL into N when stored in the db
