### ISSUE TITLE
Improve the warnings in the NerdPress menu

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#76]
We need to improve the logic in some of the warning messages in the NerdPress menu drop-downs.

Either 1A or 1B might apply:

1A. `Firewall Api Key IS set` + `Sucuri Header NOT set` + `Plugin Setting is SUCURI` = "The Sucuri Firewall appears to be inactive. Please contact us."

1B. `Firewall API key is NOT set` + `Sucuri Header IS set` = "Missing Firewall API Keys! Please contact us."

Either 2A or 2B might _also_ apply:

2A. `Sucuri plugin is not installed` = "The Sucuri Plugin is not installed! Please contact us."

2B. (This one already exists) `Sucuri plugin is inactive` = "The Sucuri Plugin is Inactive..."

**Comment by AndreyK92** [comment]
How about create a new class, that takes care setting those flags, display warnings etc?

**Comment by blogtutor** [comment]
Doesn't matter to me if it's in a new class or not. Whatever's simplest and cleanest (and doesn't take a lot of extra time...).  :)

**Comment by AndreyK92** [comment]
I would separate this functionality from Blog_Tutor_Support_Helpers class, since that class is basically just a collection of static methods.

**Comment by blogtutor** [comment]
Can't this logic just be applied when building the menu?  That's how we're currently doing it.  

(I don't envision a lot of additional notices happening in the dashboard anytime soon.)

**Comment by AndreyK92** [comment]
> doesn't take a lot of extra time
Nope, no extra time. But it would be a base class for our notification system in the near future

**Comment by blogtutor** [comment]
Ok, do whatever you think is best, and least likely to introduce any new issues.

**Comment by AndreyK92** [comment]
I opted out for leaving the methods in the Helpers file

**Comment by blogtutor** [comment]
This is looking better, but we've still got some logic problems/missing pieces. Note, the below list may be incomplete -- but this is what I've got so far in my testing this morning:

1. If the Firewall API Key is set, and the Sucuri header does not exist -- but the plugin setting is "Sucuri" it should display a warning in the menu: "The Sucuri Firewall appears to be inactive. Please contact us."  It should also not show the "Clear Cache" link.

2. If the Firewall API key is NOT set, and the Sucuri header does NOT exist -- the plugin is showing the warning that the firewall API key is not set...but it should not show this.

3. If the Sucuri Plugin is inactive, the Clear Cache link is missing (the Firewall API key still exists in the settings file, so it should still work).  The "Sucuri Plugin is Inactive" or "Sucuri Plugin is missing" messages should operate totally independently of the "Clear Cache"  link and other API key warnings.

I think before we do any more coding here, let's have another conversation to hash out ALL the logic and exactly what should be displayed when?

**Comment by AndreyK92** [comment]
Should we have a call about these?

**Comment by blogtutor** [comment]
Oh man this is all screwed up now.

When there's no Firewall API key set, the plugin isn't even showing a warning about that.

![image](https://user-images.githubusercontent.com/24479276/72580237-3c84be80-3890-11ea-9eb1-2e02e5b4091e.png)

**Comment by AndreyK92** [comment]
It's because deleting the API key causes Sucuri to purge the HTTP_X_SUCURI header. Which in turn fails to trigger line 23 flag on the Google Sheet.

**Comment by AndreyK92** [comment]
Maybe we should add an active firewall setting => sucuri to trigger that flag?

**Comment by blogtutor** [comment]
Ah! Good catch. 

I'd much rather try to autodetect, since the setting in the plugin could be incorrect very easily.

How about looking for a response header that's always added to the response when the traffic is passing through the firewall? If the `x-sucuri-cache` header is set at all, I would think that would be a good test?

![image](https://user-images.githubusercontent.com/24479276/72624962-af2b8380-38fc-11ea-81d0-eb132438379f.png)

**Comment by AndreyK92** [comment]
I don't think we can read response headers without hacking anything.
This would be one of the only ways to go `https://www.php.net/manual/en/function.headers-sent.php` but it's very unreliable/SAPI dependent.

**Comment by blogtutor** [comment]
Ok, screw it. Let's use the setting in the plugin.

So -- if the firewall api keys don't exist, AND the plugin setting is "Sucuri" let's show the "Missing Firewall API Keys! Please contact us." message.  

ALSO, I think right now that link opens the "Need Help?" tab, right?  When it does, we should have it open the "Contact Us" page.  This would be a slight modification to the existing link.

```<a href="#" onClick="window.supportHeroWidget.show('contact');">Contact Us</a>```

https://help.supporthero.io/article/show/1447-can-i-open-the-support-widget-from-a-link-in-my-app

**Comment by AndreyK92** [comment]
Do you want to change all the support hero widgets or just one for the missing firewall scenario?

**Comment by blogtutor** [comment]
I suppose anytime we say "Contact Us" it would be good to actually open the contact form. So yep, if it's quick/easy, please do change the others as well. Thanks.  (I'm really good at #ScopeCreep, clearly...)

**Comment by AndreyK92** [comment]
lol It's called Agile! And will do :)

**Comment by AndreyK92** [comment]
OK, I made the flag check for the setting being turned on instead of looking at the header. You can test!
Also added the contact part

**Comment by blogtutor** [comment]
Closed with 0.6.3.
