### ISSUE TITLE
Dashboard message for Cache Clear should be based on API response.

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#77]
If the Firewall API key is set -- but incorrect -- then we're not displaying any error message when the user clicks "clear cache." The page just reloads with no message. We need to have some kind of error message displayed in this case...

_Originally posted by @blogtutor in https://github.com/blogtutor/blog-tutor-support/issues/73#issuecomment-572355614_

**Comment by blogtutor** [comment]
Actually, I think the no-message-displaying was a holdover from cached javascript.  Now that I've cleared local caches, it seems that the "Cache was cleared..." message _does_ display, even if the API key was correct and the API response came back with an error. (I've changed the title of this issue accordingly.)

Here's the API response if the API keypair is incorrect - so we need to parse this and display an error. I think "status: 1" means success and "status: 0" means error, so we either need to hardcode a response for both scenarios, or we need to display the actual "message" that's returned (either way).

```
{
  "headers": {},
  "body": "{\"status\":0,\"action\":\"clear_cache\",\"messages\":[\"Domain was not found\"],\"request_time\":1578586658,\"output\":[],\"verbose\":1}",
  "response": {
    "code": 200,
    "message": "OK"
  },
  "cookies": [],
  "filename": null,
  "http_response": {
    "data": null,
    "headers": null,
    "status": null
  }
}
```

Here's the API response for a successful cache clear:

```{
  "headers": {},
  "body": "{\"status\":1,\"action\":\"clear_cache\",\"messages\":[\"The cache for the domain \\\"dev.blogtutor.com\\\" is being cleared. Note that it may take up to two minutes for it to be fully flushed.\"],\"request_time\":1578586885,\"output\":[],\"verbose\":1}",
  "response": {
    "code": 200,
    "message": "OK"
  },
  "cookies": [],
  "filename": null,
  "http_response": {
    "data": null,
    "headers": null,
    "status": null
  }
}
```

**Comment by blogtutor** [comment]
This looks good now!

Just needs one more tweak... please make the text of the error message red (`#FF0000`), and add "Heads up!" to the beginning of the error message?

**Comment by blogtutor** [comment]
Also, let's make left-border of the notice red, too -- using the standard WP error colors. (We're using our brand blue/purple to match the "n" logo, which is fine for success messages...but I"d rather error messages be more obvious.). I think there's a built-in class for this, `class="error notice"`.

**Comment by blogtutor** [comment]
Okay, so this might be a little paranoid, but... Shouldn't we sanitize the API response before echoing it?  

I'm looking at class-support-clearcache.php - lines 45-59.  I know we're only displaying if it's a "success" response, but since this is coming from a third-party source, we should not fully trust it.  How about adding `sanitize_text_field()` (or a similar function) to the echo on line 59 ?

**Comment by AndreyK92** [comment]
IMO, `sanitize_text_field()` would not be necessary here since. In case of a malformed/nefarious response the `json_decode()` on line 47 will throw an error and the execution will terminate

**Comment by blogtutor** [comment]
What if it's a valid JSON response, but a malicious one (say, with some javascript in it)?

**Comment by AndreyK92** [comment]
I think you're right. I read up on `json_decode` and it escapes only some characters, I was able to inject some JS in this way on my local setup. I'll sanitize the string before outputting it!

**Comment by blogtutor** [comment]
Great, thanks. Also, just so it doesn't get lost in the shuffle -- did you see the comments earlier on this issue about changing the error message color?

> This looks good now!
> 
> Just needs one more tweak... please make the text of the error message red (`#FF0000`), and add "Heads up!" to the beginning of the error message?

> Also, **_only if it's easy and quick_**, let's make left-border of the notice red, too -- using the standard WP error colors. (We're using our brand blue/purple to match the "n" logo, which is fine for success messages...but I"d rather error messages be more obvious.). I think there's a built-in class for this, `class="error notice"`.

**Comment by AndreyK92** [comment]
Yup! I saw those :+1:

**Comment by AndreyK92** [comment]
@blogtutor Did you see this string `There was a problem clearing the Sucuri Firewall cache. Please try again, and if it still doesn\'t work please contact support@nerdpress.net.` when the clearing failed?

**Comment by blogtutor** [comment]
Yes. It worked correctly. It's just too easy not to realize it's an error message. (People don't read carefully!). Adding the "Heads up!" and making the text `#FF0000` would make it much more obvious it's an error.

**Comment by AndreyK92** [comment]
This is ready to be tested on the dev site :)
