### ISSUE TITLE
Show error message if IP address fails to be whitelisted

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#79]
I just ran into an issue on a site where the Firewall API Keypair was incorrect... so she wasn't getting automatically whitelisted... But there was also no error message provided.  

I thought we had set things up so that the top-right purple notification would display an error message based on the API response?  If we did, it didn't work properly... and if we didn't, let's discuss what to do in this situation...

**Comment by blogtutor** [comment]
It would probably also be good if this triggered a notification to us...

**Comment by AndreyK92** [comment]
I think we should leave a generic message. You can test it out on the server... Let me know what you think.

**Comment by blogtutor** [comment]
I'm fine with a generic message.

Just saw this on the Dev site (below).

How about we change the language to this:

**Heads up! Automatically whitelisting your IP address on the Sucuri Firewall didn't work. If the problem persists, please contact us at support@nerdpress.net.**

and might as well make the email address a clickable mailto: link if we can.

![image](https://user-images.githubusercontent.com/24479276/72567215-47c4f380-386a-11ea-8408-e83e5c056019.png)

**Comment by blogtutor** [comment]
Oh! Can we also add an "warning" emoji at the start? ⚠

That will help make it more obvious that it's an error message.

**Comment by AndreyK92** [comment]
Good idea. Will do!

**Comment by AndreyK92** [comment]
OK, I made the changes. Hope it looks good!

**Comment by blogtutor** [comment]
The emoji isn't quite as fancy as I'd hoped, but I'll live with it.

Can you please do two more quick changes:
1. Change the color of the mail link to dark blue (or anything with better contrast) - it's illegible right now.
2. Make "Heads up!" bold.

![image](https://user-images.githubusercontent.com/24479276/72572405-42ba7100-3877-11ea-996a-9c1965f9f716.png)

**Comment by blogtutor** [comment]
Color code for the NerdPress blue (for the email address) - #0F145B

**Comment by AndreyK92** [comment]
![Screenshot from 2020-01-16 16-17-45](https://user-images.githubusercontent.com/23062177/72573867-e7d74880-387b-11ea-944a-aac6ba3da3cf.png)

**Comment by AndreyK92** [comment]
This is done now
![Screenshot from 2020-01-17 09-55-20](https://user-images.githubusercontent.com/23062177/72634483-89f44080-390f-11ea-90b3-375037df4f1e.png)

**Comment by blogtutor** [comment]
Yay! Looks good. Thanks.

**Comment by blogtutor** [comment]
Closed via 0.6.3.
