### ISSUE TITLE
Switch to private Github Repo

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#8]
Adjust the updater script to pull from a private repo.  😅

**Comment by blogtutor** [comment]
Hey it's time to do this. @ecotechie has some good ideas but I want you all to discuss and find the best plan. @jchristopher @1337rout

**Comment by jchristopher** [comment]
There are pros/cons to GitHub-based updates vs self hosted (as per link above)

Is that the starting point of the discussion, or is it (mostly) settled that GitHub-based is the way to go?

I don’t really have a weighted opinion, but many times (as more tech builds up) it can be nice to _not_ have to ensure the repo structure meets the requirements of WP plugins.

Self hosting the updates can still allow for automated deployments from GitHub, but also implement a bundling step that organizes (and minimizes) what’s shipped over the wire. Just food for thought 👍

**Comment by 1337rout** [comment]
I'm probably missing some context here...but,

We already have a kernl.us license for Hubbub, could we use that to handle updates?

**Comment by blogtutor** [comment]
The primary goal here is to make our repo private, especially as we're considering adding more security-related features.  (I recognize that "Security through obscurity" isn't "Secure" but if we don't broadcast our code to the open web then it's not visible for everyone to see (the only folks who would even be aware of it are site owners/web hosts/etc.).

We built GitHub Updater Lite into the plugin because we found it and it worked well at the time.  But it requires the repo to be public.

Kernl.us is "okay" but we don't _love_ it. The reports are neat but they're also wildly inaccurate. We should probably get Colin's opinion on using Kernl more vs. less, long-term.

Sergio said that WordPress core can now handle third-party plugins more natively, but I'm not sure the details on that so we should explore that. 

Also, one feature I really do like about our current GitHub setup is the "Releases" functionality. It's a nice interface, is useful to have listed directly inside Github (not buried in a readme somewhere), and automatically imports into the details modal inside WP.

**Comment by ecotechie** [comment]
I have a working MVP example in a local branch that uses the Update URI feature:
https://make.wordpress.org/core/2021/06/29/introducing-update-uri-plugin-header-in-wordpress-5-8/

https://developer.wordpress.org/reference/hooks/update_plugins_hostname/

**Comment by ecotechie** [comment]
I have a working MVP example in a local branch that uses the Update URI feature:
https://make.wordpress.org/core/2021/06/29/introducing-update-uri-plugin-header-in-wordpress-5-8/

https://developer.wordpress.org/reference/hooks/update_plugins_hostname/

This is what I have so far:
https://github.com/blogtutor/blog-tutor-support/tree/update

**Comment by ecotechie** [comment]
We set the Update URI on the main plugin file's dock block:
https://github.com/blogtutor/blog-tutor-support/blob/update/blog-tutor-support.php#L10

Then call that URL here:
https://github.com/blogtutor/blog-tutor-support/blob/update/includes/class-support-update.php#L97

When this filter runs:
https://github.com/blogtutor/blog-tutor-support/blob/update/includes/class-support-update.php#L55
