### ISSUE TITLE
Improve colors on "Problem clearing Sucuri Cache" dashboard message.

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#80]
![image](https://user-images.githubusercontent.com/24479276/72579134-fed26680-388c-11ea-8200-9c27b15b54ce.png)

I'd like the error message text ("There was a problem clearing...") to be red too. `#ff0000`

And, if there's an existing WP Rocket dashboard message, the WP Rocket message left-border color is getting changed to the NerdPress Blue for some reason. It's normally yellow/amber. Not a big deal (this is an uncommon case), but I want to be sure it's not going to cause other issues elsewhere.

**Comment by blogtutor** [comment]
@AndreyK92 Did you see this one I added last night? 

> ![image](https://user-images.githubusercontent.com/24479276/72579134-fed26680-388c-11ea-8200-9c27b15b54ce.png)
> 
> I'd like the error message text ("There was a problem clearing...") to be red too. `#ff0000`
> 
> And, if there's an existing WP Rocket dashboard message, the WP Rocket message left-border color is getting changed to the NerdPress Blue for some reason. It's normally yellow/amber. Not a big deal (this is an uncommon case), but I want to be sure it's not going to cause other issues elsewhere.

**Comment by AndreyK92** [comment]
@blogtutor This is fixed.
WP Rocket notice's class is "notice" (lol) so my styling also affected it. Good catch!

**Comment by blogtutor** [comment]
@AndreyK92 So, umm, the cache clear "success" message text is now red. I only wanted the error message to be red...

![image](https://user-images.githubusercontent.com/24479276/72656005-5801cf00-394d-11ea-8e57-33f651efa3ed.png)

**Comment by AndreyK92** [comment]
Ok, just changed the color :)

**Comment by blogtutor** [comment]
Yay!  Ok, I think this is all set now then. 😅
