### ISSUE TITLE
Create temporary plugin for testing Cloudflare cache clearing

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#91]
We need to create a plugin that will be used for testing the new Cloudflare setup... it will need to clear the Cloudflare Cache for a specific hostname using their API.

If we build the plugin off of the Sucuri Flush plugin, it should be pretty quick to implement. See code here:
https://plugins.trac.wordpress.org/browser/sucuri-flush/trunk/sucuri-flush.php

Cloudflare API Docs here:
https://api.cloudflare.com/#zone-purge-files-by-cache-tags-or-host

The Sucuri Flush plugin already has a settings page and a form field for entering a URL. We can use that to enter the hostname of the site, and then hard code everything else in the plugin file (including the API Token for now).

Right now I think it only triggers a flush on the `save_post` action -- which might be fine?  We may also want to add a link in the top menu ~(maybe inside the existing NerdPress drop-down?)~ to do a manual cache flush.

Let's also make the settings page for this visible only to Nerdpress users.

**Comment by AndreyK92** [comment]
> (maybe inside the existing NerdPress drop-down?)
Could be a little tricky, since it's a separate plugin. It can be done but would be hacky

**Comment by blogtutor** [comment]
Ok, then definitely skip the menu integration for now.  If you are able to add a link, just make it a link directly in the top admin bar - "Clear Cloudflare Cache". Thanks.

**Comment by AndreyK92** [comment]
Roger, I think it's a good idea!
