### ISSUE TITLE
Update plugin description

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#95]
Remove reference to specific Firewall(s)...

**Comment by blogtutor** [comment]
_Change from this:_

> Helps your site work better with the Sucuri Firewall, and adds the NerdPress "Need Help?" support tab to your dashboard for easy access to our knowledge base and contact form.

_To this:_

> Helps your site work with the Cloudflare Enterprise or Sucuri Firewall, and adds the NerdPress "Need Help?" support tab to your dashboard.

**Comment by ecotechie** [comment]
Maybe change "Cloudflare Enterprise" to NerdPress' exclusive Cloudflare Enterprise" or such?

**Comment by blogtutor** [comment]
Ok, how about this?  A little clunkier, but better?

Helps your site work with our custom Cloudflare Enterprise setup or the Sucuri Firewall, and adds the NerdPress "Need Help?" support tab to your dashboard.

**Comment by ecotechie** [comment]
Done
