### ISSUE TITLE
Hide WP Rocket's HelpScout Beacon

### ISSUE THREAD

**Issue by blogtutor** [blogtutor/blog-tutor-support#96]
We still have clients submitting support requests with WP Rocket through their beacon, when they're on the WP Rocket settings page... But they should be coming to us for support, not WP Rocket.

I think we may be able to hide their beacon with some simple CSS:

```
div#beacon-container {
    display: none;
}
```

Let's look at adding that on WP Rocket admin pages and see if we can get that to work reliably?

**Comment by ecotechie** [comment]
Doneso!
